/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsRouteRouteImport } from './routes/_ops/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as OpsActiveMovementsRouteImport } from './routes/_ops/active-movements'
import { Route as OpsBulkLogisticsRouteImport } from './routes/_ops/bulk-logistics'
import { Route as OpsComplianceRouteImport } from './routes/_ops/compliance'
import { Route as OpsDeliveriesRouteImport } from './routes/_ops/deliveries'
import { Route as OpsDocumentsRouteImport } from './routes/_ops/documents'
import { Route as OpsDriversRouteImport } from './routes/_ops/drivers'
import { Route as OpsFleetRouteImport } from './routes/_ops/fleet'
import { Route as OpsIncidentsRouteImport } from './routes/_ops/incidents'
import { Route as OpsNotificationsRouteImport } from './routes/_ops/notifications'
import { Route as OpsPaymentsRouteImport } from './routes/_ops/payments'
import { Route as OpsReportsRouteImport } from './routes/_ops/reports'
import { Route as OpsRoutesTrackingRouteImport } from './routes/_ops/routes-tracking'
import { Route as OpsSampleLogisticsRouteImport } from './routes/_ops/sample-logistics'
import { Route as OpsSettingsRouteImport } from './routes/_ops/settings'
import { Route as OpsTransactionsRouteImport } from './routes/_ops/transactions'
import { Route as OpsTransportRequestsRouteImport } from './routes/_ops/transport-requests'
import { Route as OpsVehiclesRouteImport } from './routes/_ops/vehicles'
import { Route as OpsDriversDriverIdRouteImport } from './routes/_ops/drivers_.$driverId'
import { Route as OpsMovementsMovementIdRouteImport } from './routes/_ops/movements.$movementId'
import { Route as OpsTransactionsTxnIdRouteImport } from './routes/_ops/transactions_.$txnId'
import { Route as OpsTransportRequestsRequestIdRouteImport } from './routes/_ops/transport-requests_.$requestId'
import { Route as OpsVehiclesVehicleIdRouteImport } from './routes/_ops/vehicles_.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRouteRoute = OpsRouteRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsActiveMovementsRoute = OpsActiveMovementsRouteImport.update({
  id: '/active-movements',
  path: '/active-movements',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsBulkLogisticsRoute = OpsBulkLogisticsRouteImport.update({
  id: '/bulk-logistics',
  path: '/bulk-logistics',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsComplianceRoute = OpsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsDeliveriesRoute = OpsDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsDocumentsRoute = OpsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsDriversRoute = OpsDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsFleetRoute = OpsFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsIncidentsRoute = OpsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsNotificationsRoute = OpsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsPaymentsRoute = OpsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsReportsRoute = OpsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsRoutesTrackingRoute = OpsRoutesTrackingRouteImport.update({
  id: '/routes-tracking',
  path: '/routes-tracking',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsSampleLogisticsRoute = OpsSampleLogisticsRouteImport.update({
  id: '/sample-logistics',
  path: '/sample-logistics',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsSettingsRoute = OpsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsTransactionsRoute = OpsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsTransportRequestsRoute = OpsTransportRequestsRouteImport.update({
  id: '/transport-requests',
  path: '/transport-requests',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsVehiclesRoute = OpsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsDriversDriverIdRoute = OpsDriversDriverIdRouteImport.update({
  id: '/drivers_/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsMovementsMovementIdRoute = OpsMovementsMovementIdRouteImport.update({
  id: '/movements/$movementId',
  path: '/movements/$movementId',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsTransactionsTxnIdRoute = OpsTransactionsTxnIdRouteImport.update({
  id: '/transactions_/$txnId',
  path: '/transactions/$txnId',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsTransportRequestsRequestIdRoute =
  OpsTransportRequestsRequestIdRouteImport.update({
    id: '/transport-requests_/$requestId',
    path: '/transport-requests/$requestId',
    getParentRoute: () => OpsRouteRoute,
  } as any)
const OpsVehiclesVehicleIdRoute = OpsVehiclesVehicleIdRouteImport.update({
  id: '/vehicles_/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => OpsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/active-movements': typeof OpsActiveMovementsRoute
  '/bulk-logistics': typeof OpsBulkLogisticsRoute
  '/compliance': typeof OpsComplianceRoute
  '/deliveries': typeof OpsDeliveriesRoute
  '/documents': typeof OpsDocumentsRoute
  '/drivers': typeof OpsDriversRoute
  '/fleet': typeof OpsFleetRoute
  '/incidents': typeof OpsIncidentsRoute
  '/notifications': typeof OpsNotificationsRoute
  '/payments': typeof OpsPaymentsRoute
  '/reports': typeof OpsReportsRoute
  '/routes-tracking': typeof OpsRoutesTrackingRoute
  '/sample-logistics': typeof OpsSampleLogisticsRoute
  '/settings': typeof OpsSettingsRoute
  '/transactions': typeof OpsTransactionsRoute
  '/transport-requests': typeof OpsTransportRequestsRoute
  '/vehicles': typeof OpsVehiclesRoute
  '/drivers/$driverId': typeof OpsDriversDriverIdRoute
  '/movements/$movementId': typeof OpsMovementsMovementIdRoute
  '/transactions/$txnId': typeof OpsTransactionsTxnIdRoute
  '/transport-requests/$requestId': typeof OpsTransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof OpsVehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/active-movements': typeof OpsActiveMovementsRoute
  '/bulk-logistics': typeof OpsBulkLogisticsRoute
  '/compliance': typeof OpsComplianceRoute
  '/deliveries': typeof OpsDeliveriesRoute
  '/documents': typeof OpsDocumentsRoute
  '/drivers': typeof OpsDriversRoute
  '/fleet': typeof OpsFleetRoute
  '/incidents': typeof OpsIncidentsRoute
  '/notifications': typeof OpsNotificationsRoute
  '/payments': typeof OpsPaymentsRoute
  '/reports': typeof OpsReportsRoute
  '/routes-tracking': typeof OpsRoutesTrackingRoute
  '/sample-logistics': typeof OpsSampleLogisticsRoute
  '/settings': typeof OpsSettingsRoute
  '/transactions': typeof OpsTransactionsRoute
  '/transport-requests': typeof OpsTransportRequestsRoute
  '/vehicles': typeof OpsVehiclesRoute
  '/drivers/$driverId': typeof OpsDriversDriverIdRoute
  '/movements/$movementId': typeof OpsMovementsMovementIdRoute
  '/transactions/$txnId': typeof OpsTransactionsTxnIdRoute
  '/transport-requests/$requestId': typeof OpsTransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof OpsVehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_ops': typeof OpsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_ops/active-movements': typeof OpsActiveMovementsRoute
  '/_ops/bulk-logistics': typeof OpsBulkLogisticsRoute
  '/_ops/compliance': typeof OpsComplianceRoute
  '/_ops/deliveries': typeof OpsDeliveriesRoute
  '/_ops/documents': typeof OpsDocumentsRoute
  '/_ops/drivers': typeof OpsDriversRoute
  '/_ops/fleet': typeof OpsFleetRoute
  '/_ops/incidents': typeof OpsIncidentsRoute
  '/_ops/notifications': typeof OpsNotificationsRoute
  '/_ops/payments': typeof OpsPaymentsRoute
  '/_ops/reports': typeof OpsReportsRoute
  '/_ops/routes-tracking': typeof OpsRoutesTrackingRoute
  '/_ops/sample-logistics': typeof OpsSampleLogisticsRoute
  '/_ops/settings': typeof OpsSettingsRoute
  '/_ops/transactions': typeof OpsTransactionsRoute
  '/_ops/transport-requests': typeof OpsTransportRequestsRoute
  '/_ops/vehicles': typeof OpsVehiclesRoute
  '/_ops/drivers_/$driverId': typeof OpsDriversDriverIdRoute
  '/_ops/movements/$movementId': typeof OpsMovementsMovementIdRoute
  '/_ops/transactions_/$txnId': typeof OpsTransactionsTxnIdRoute
  '/_ops/transport-requests_/$requestId': typeof OpsTransportRequestsRequestIdRoute
  '/_ops/vehicles_/$vehicleId': typeof OpsVehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/active-movements'
    | '/bulk-logistics'
    | '/compliance'
    | '/deliveries'
    | '/documents'
    | '/drivers'
    | '/fleet'
    | '/incidents'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/routes-tracking'
    | '/sample-logistics'
    | '/settings'
    | '/transactions'
    | '/transport-requests'
    | '/vehicles'
    | '/drivers/$driverId'
    | '/movements/$movementId'
    | '/transactions/$txnId'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/active-movements'
    | '/bulk-logistics'
    | '/compliance'
    | '/deliveries'
    | '/documents'
    | '/drivers'
    | '/fleet'
    | '/incidents'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/routes-tracking'
    | '/sample-logistics'
    | '/settings'
    | '/transactions'
    | '/transport-requests'
    | '/vehicles'
    | '/drivers/$driverId'
    | '/movements/$movementId'
    | '/transactions/$txnId'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/_ops'
    | '/sign-in'
    | '/sign-up'
    | '/_ops/active-movements'
    | '/_ops/bulk-logistics'
    | '/_ops/compliance'
    | '/_ops/deliveries'
    | '/_ops/documents'
    | '/_ops/drivers'
    | '/_ops/fleet'
    | '/_ops/incidents'
    | '/_ops/notifications'
    | '/_ops/payments'
    | '/_ops/reports'
    | '/_ops/routes-tracking'
    | '/_ops/sample-logistics'
    | '/_ops/settings'
    | '/_ops/transactions'
    | '/_ops/transport-requests'
    | '/_ops/vehicles'
    | '/_ops/drivers_/$driverId'
    | '/_ops/movements/$movementId'
    | '/_ops/transactions_/$txnId'
    | '/_ops/transport-requests_/$requestId'
    | '/_ops/vehicles_/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRouteRoute: typeof OpsRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops/active-movements': {
      id: '/_ops/active-movements'
      path: '/active-movements'
      fullPath: '/active-movements'
      preLoaderRoute: typeof OpsActiveMovementsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/bulk-logistics': {
      id: '/_ops/bulk-logistics'
      path: '/bulk-logistics'
      fullPath: '/bulk-logistics'
      preLoaderRoute: typeof OpsBulkLogisticsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/compliance': {
      id: '/_ops/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof OpsComplianceRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/deliveries': {
      id: '/_ops/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof OpsDeliveriesRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/documents': {
      id: '/_ops/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof OpsDocumentsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/drivers': {
      id: '/_ops/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof OpsDriversRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/fleet': {
      id: '/_ops/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof OpsFleetRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/incidents': {
      id: '/_ops/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof OpsIncidentsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/notifications': {
      id: '/_ops/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof OpsNotificationsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/payments': {
      id: '/_ops/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof OpsPaymentsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/reports': {
      id: '/_ops/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof OpsReportsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/routes-tracking': {
      id: '/_ops/routes-tracking'
      path: '/routes-tracking'
      fullPath: '/routes-tracking'
      preLoaderRoute: typeof OpsRoutesTrackingRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/sample-logistics': {
      id: '/_ops/sample-logistics'
      path: '/sample-logistics'
      fullPath: '/sample-logistics'
      preLoaderRoute: typeof OpsSampleLogisticsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/settings': {
      id: '/_ops/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OpsSettingsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/transactions': {
      id: '/_ops/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof OpsTransactionsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/transport-requests': {
      id: '/_ops/transport-requests'
      path: '/transport-requests'
      fullPath: '/transport-requests'
      preLoaderRoute: typeof OpsTransportRequestsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/vehicles': {
      id: '/_ops/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof OpsVehiclesRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/drivers_/$driverId': {
      id: '/_ops/drivers_/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof OpsDriversDriverIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/movements/$movementId': {
      id: '/_ops/movements/$movementId'
      path: '/movements/$movementId'
      fullPath: '/movements/$movementId'
      preLoaderRoute: typeof OpsMovementsMovementIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/transactions_/$txnId': {
      id: '/_ops/transactions_/$txnId'
      path: '/transactions/$txnId'
      fullPath: '/transactions/$txnId'
      preLoaderRoute: typeof OpsTransactionsTxnIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/transport-requests_/$requestId': {
      id: '/_ops/transport-requests_/$requestId'
      path: '/transport-requests/$requestId'
      fullPath: '/transport-requests/$requestId'
      preLoaderRoute: typeof OpsTransportRequestsRequestIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/_ops/vehicles_/$vehicleId': {
      id: '/_ops/vehicles_/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof OpsVehiclesVehicleIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
  }
}

interface OpsRouteRouteChildren {
  OpsActiveMovementsRoute: typeof OpsActiveMovementsRoute
  OpsBulkLogisticsRoute: typeof OpsBulkLogisticsRoute
  OpsComplianceRoute: typeof OpsComplianceRoute
  OpsDeliveriesRoute: typeof OpsDeliveriesRoute
  OpsDocumentsRoute: typeof OpsDocumentsRoute
  OpsDriversRoute: typeof OpsDriversRoute
  OpsFleetRoute: typeof OpsFleetRoute
  OpsIncidentsRoute: typeof OpsIncidentsRoute
  OpsNotificationsRoute: typeof OpsNotificationsRoute
  OpsPaymentsRoute: typeof OpsPaymentsRoute
  OpsReportsRoute: typeof OpsReportsRoute
  OpsRoutesTrackingRoute: typeof OpsRoutesTrackingRoute
  OpsSampleLogisticsRoute: typeof OpsSampleLogisticsRoute
  OpsSettingsRoute: typeof OpsSettingsRoute
  OpsTransactionsRoute: typeof OpsTransactionsRoute
  OpsTransportRequestsRoute: typeof OpsTransportRequestsRoute
  OpsVehiclesRoute: typeof OpsVehiclesRoute
  OpsDriversDriverIdRoute: typeof OpsDriversDriverIdRoute
  OpsMovementsMovementIdRoute: typeof OpsMovementsMovementIdRoute
  OpsTransactionsTxnIdRoute: typeof OpsTransactionsTxnIdRoute
  OpsTransportRequestsRequestIdRoute: typeof OpsTransportRequestsRequestIdRoute
  OpsVehiclesVehicleIdRoute: typeof OpsVehiclesVehicleIdRoute
}

const OpsRouteRouteChildren: OpsRouteRouteChildren = {
  OpsActiveMovementsRoute: OpsActiveMovementsRoute,
  OpsBulkLogisticsRoute: OpsBulkLogisticsRoute,
  OpsComplianceRoute: OpsComplianceRoute,
  OpsDeliveriesRoute: OpsDeliveriesRoute,
  OpsDocumentsRoute: OpsDocumentsRoute,
  OpsDriversRoute: OpsDriversRoute,
  OpsFleetRoute: OpsFleetRoute,
  OpsIncidentsRoute: OpsIncidentsRoute,
  OpsNotificationsRoute: OpsNotificationsRoute,
  OpsPaymentsRoute: OpsPaymentsRoute,
  OpsReportsRoute: OpsReportsRoute,
  OpsRoutesTrackingRoute: OpsRoutesTrackingRoute,
  OpsSampleLogisticsRoute: OpsSampleLogisticsRoute,
  OpsSettingsRoute: OpsSettingsRoute,
  OpsTransactionsRoute: OpsTransactionsRoute,
  OpsTransportRequestsRoute: OpsTransportRequestsRoute,
  OpsVehiclesRoute: OpsVehiclesRoute,
  OpsDriversDriverIdRoute: OpsDriversDriverIdRoute,
  OpsMovementsMovementIdRoute: OpsMovementsMovementIdRoute,
  OpsTransactionsTxnIdRoute: OpsTransactionsTxnIdRoute,
  OpsTransportRequestsRequestIdRoute: OpsTransportRequestsRequestIdRoute,
  OpsVehiclesVehicleIdRoute: OpsVehiclesVehicleIdRoute,
}

const OpsRouteRouteWithChildren = OpsRouteRoute._addFileChildren(
  OpsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRouteRoute: OpsRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
