/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalActiveMovementsRouteImport } from './routes/portal/active-movements'
import { Route as PortalApplicationRecordRouteImport } from './routes/portal/application-record'
import { Route as PortalBulkLogisticsRouteImport } from './routes/portal/bulk-logistics'
import { Route as PortalComplianceRouteImport } from './routes/portal/compliance'
import { Route as PortalDeliveriesRouteImport } from './routes/portal/deliveries'
import { Route as PortalDocumentsRouteImport } from './routes/portal/documents'
import { Route as PortalDriversRouteImport } from './routes/portal/drivers'
import { Route as PortalFleetRouteImport } from './routes/portal/fleet'
import { Route as PortalIncidentsRouteImport } from './routes/portal/incidents'
import { Route as PortalNotificationsRouteImport } from './routes/portal/notifications'
import { Route as PortalPaymentsRouteImport } from './routes/portal/payments'
import { Route as PortalReportsRouteImport } from './routes/portal/reports'
import { Route as PortalRequestsRouteImport } from './routes/portal/requests'
import { Route as PortalRoutesTrackingRouteImport } from './routes/portal/routes-tracking'
import { Route as PortalSampleLogisticsRouteImport } from './routes/portal/sample-logistics'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalTransactionsRouteImport } from './routes/portal/transactions'
import { Route as PortalTransportRequestsRouteImport } from './routes/portal/transport-requests'
import { Route as PortalVehiclesRouteImport } from './routes/portal/vehicles'
import { Route as PortalDriversDriverIdRouteImport } from './routes/portal/drivers_.$driverId'
import { Route as PortalMovementsMovementIdRouteImport } from './routes/portal/movements.$movementId'
import { Route as PortalTransactionsTxnIdRouteImport } from './routes/portal/transactions_.$txnId'
import { Route as PortalTransportRequestsRequestIdRouteImport } from './routes/portal/transport-requests_.$requestId'
import { Route as PortalVehiclesVehicleIdRouteImport } from './routes/portal/vehicles_.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalActiveMovementsRoute = PortalActiveMovementsRouteImport.update({
  id: '/active-movements',
  path: '/active-movements',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalApplicationRecordRoute = PortalApplicationRecordRouteImport.update({
  id: '/application-record',
  path: '/application-record',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalBulkLogisticsRoute = PortalBulkLogisticsRouteImport.update({
  id: '/bulk-logistics',
  path: '/bulk-logistics',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalComplianceRoute = PortalComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDeliveriesRoute = PortalDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDriversRoute = PortalDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalFleetRoute = PortalFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalIncidentsRoute = PortalIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalRequestsRoute = PortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalRoutesTrackingRoute = PortalRoutesTrackingRouteImport.update({
  id: '/routes-tracking',
  path: '/routes-tracking',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSampleLogisticsRoute = PortalSampleLogisticsRouteImport.update({
  id: '/sample-logistics',
  path: '/sample-logistics',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTransactionsRoute = PortalTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTransportRequestsRoute = PortalTransportRequestsRouteImport.update({
  id: '/transport-requests',
  path: '/transport-requests',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalVehiclesRoute = PortalVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDriversDriverIdRoute = PortalDriversDriverIdRouteImport.update({
  id: '/drivers_/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMovementsMovementIdRoute =
  PortalMovementsMovementIdRouteImport.update({
    id: '/movements/$movementId',
    path: '/movements/$movementId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTransactionsTxnIdRoute = PortalTransactionsTxnIdRouteImport.update({
  id: '/transactions_/$txnId',
  path: '/transactions/$txnId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTransportRequestsRequestIdRoute =
  PortalTransportRequestsRequestIdRouteImport.update({
    id: '/transport-requests_/$requestId',
    path: '/transport-requests/$requestId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalVehiclesVehicleIdRoute = PortalVehiclesVehicleIdRouteImport.update({
  id: '/vehicles_/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/submitted': typeof SubmittedRoute
  '/verify': typeof VerifyRoute
  '/portal/active-movements': typeof PortalActiveMovementsRoute
  '/portal/application-record': typeof PortalApplicationRecordRoute
  '/portal/bulk-logistics': typeof PortalBulkLogisticsRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/deliveries': typeof PortalDeliveriesRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/drivers': typeof PortalDriversRoute
  '/portal/fleet': typeof PortalFleetRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/routes-tracking': typeof PortalRoutesTrackingRoute
  '/portal/sample-logistics': typeof PortalSampleLogisticsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/transport-requests': typeof PortalTransportRequestsRoute
  '/portal/vehicles': typeof PortalVehiclesRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/drivers/$driverId': typeof PortalDriversDriverIdRoute
  '/portal/movements/$movementId': typeof PortalMovementsMovementIdRoute
  '/portal/transactions/$txnId': typeof PortalTransactionsTxnIdRoute
  '/portal/transport-requests/$requestId': typeof PortalTransportRequestsRequestIdRoute
  '/portal/vehicles/$vehicleId': typeof PortalVehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/submitted': typeof SubmittedRoute
  '/verify': typeof VerifyRoute
  '/portal/active-movements': typeof PortalActiveMovementsRoute
  '/portal/application-record': typeof PortalApplicationRecordRoute
  '/portal/bulk-logistics': typeof PortalBulkLogisticsRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/deliveries': typeof PortalDeliveriesRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/drivers': typeof PortalDriversRoute
  '/portal/fleet': typeof PortalFleetRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/routes-tracking': typeof PortalRoutesTrackingRoute
  '/portal/sample-logistics': typeof PortalSampleLogisticsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/transport-requests': typeof PortalTransportRequestsRoute
  '/portal/vehicles': typeof PortalVehiclesRoute
  '/portal': typeof PortalIndexRoute
  '/portal/drivers/$driverId': typeof PortalDriversDriverIdRoute
  '/portal/movements/$movementId': typeof PortalMovementsMovementIdRoute
  '/portal/transactions/$txnId': typeof PortalTransactionsTxnIdRoute
  '/portal/transport-requests/$requestId': typeof PortalTransportRequestsRequestIdRoute
  '/portal/vehicles/$vehicleId': typeof PortalVehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/submitted': typeof SubmittedRoute
  '/verify': typeof VerifyRoute
  '/portal/active-movements': typeof PortalActiveMovementsRoute
  '/portal/application-record': typeof PortalApplicationRecordRoute
  '/portal/bulk-logistics': typeof PortalBulkLogisticsRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/deliveries': typeof PortalDeliveriesRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/drivers': typeof PortalDriversRoute
  '/portal/fleet': typeof PortalFleetRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/routes-tracking': typeof PortalRoutesTrackingRoute
  '/portal/sample-logistics': typeof PortalSampleLogisticsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/transport-requests': typeof PortalTransportRequestsRoute
  '/portal/vehicles': typeof PortalVehiclesRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/drivers_/$driverId': typeof PortalDriversDriverIdRoute
  '/portal/movements/$movementId': typeof PortalMovementsMovementIdRoute
  '/portal/transactions_/$txnId': typeof PortalTransactionsTxnIdRoute
  '/portal/transport-requests_/$requestId': typeof PortalTransportRequestsRequestIdRoute
  '/portal/vehicles_/$vehicleId': typeof PortalVehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/application'
    | '/auth'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/submitted'
    | '/verify'
    | '/portal/active-movements'
    | '/portal/application-record'
    | '/portal/bulk-logistics'
    | '/portal/compliance'
    | '/portal/deliveries'
    | '/portal/documents'
    | '/portal/drivers'
    | '/portal/fleet'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/reports'
    | '/portal/requests'
    | '/portal/routes-tracking'
    | '/portal/sample-logistics'
    | '/portal/settings'
    | '/portal/transactions'
    | '/portal/transport-requests'
    | '/portal/vehicles'
    | '/portal/'
    | '/portal/drivers/$driverId'
    | '/portal/movements/$movementId'
    | '/portal/transactions/$txnId'
    | '/portal/transport-requests/$requestId'
    | '/portal/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application'
    | '/auth'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/submitted'
    | '/verify'
    | '/portal/active-movements'
    | '/portal/application-record'
    | '/portal/bulk-logistics'
    | '/portal/compliance'
    | '/portal/deliveries'
    | '/portal/documents'
    | '/portal/drivers'
    | '/portal/fleet'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/reports'
    | '/portal/requests'
    | '/portal/routes-tracking'
    | '/portal/sample-logistics'
    | '/portal/settings'
    | '/portal/transactions'
    | '/portal/transport-requests'
    | '/portal/vehicles'
    | '/portal'
    | '/portal/drivers/$driverId'
    | '/portal/movements/$movementId'
    | '/portal/transactions/$txnId'
    | '/portal/transport-requests/$requestId'
    | '/portal/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/application'
    | '/auth'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/submitted'
    | '/verify'
    | '/portal/active-movements'
    | '/portal/application-record'
    | '/portal/bulk-logistics'
    | '/portal/compliance'
    | '/portal/deliveries'
    | '/portal/documents'
    | '/portal/drivers'
    | '/portal/fleet'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/reports'
    | '/portal/requests'
    | '/portal/routes-tracking'
    | '/portal/sample-logistics'
    | '/portal/settings'
    | '/portal/transactions'
    | '/portal/transport-requests'
    | '/portal/vehicles'
    | '/portal/'
    | '/portal/drivers_/$driverId'
    | '/portal/movements/$movementId'
    | '/portal/transactions_/$txnId'
    | '/portal/transport-requests_/$requestId'
    | '/portal/vehicles_/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  ApplicationRoute: typeof ApplicationRoute
  AuthRoute: typeof AuthRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  SubmittedRoute: typeof SubmittedRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/active-movements': {
      id: '/portal/active-movements'
      path: '/active-movements'
      fullPath: '/portal/active-movements'
      preLoaderRoute: typeof PortalActiveMovementsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/application-record': {
      id: '/portal/application-record'
      path: '/application-record'
      fullPath: '/portal/application-record'
      preLoaderRoute: typeof PortalApplicationRecordRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/bulk-logistics': {
      id: '/portal/bulk-logistics'
      path: '/bulk-logistics'
      fullPath: '/portal/bulk-logistics'
      preLoaderRoute: typeof PortalBulkLogisticsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/compliance': {
      id: '/portal/compliance'
      path: '/compliance'
      fullPath: '/portal/compliance'
      preLoaderRoute: typeof PortalComplianceRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/deliveries': {
      id: '/portal/deliveries'
      path: '/deliveries'
      fullPath: '/portal/deliveries'
      preLoaderRoute: typeof PortalDeliveriesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/drivers': {
      id: '/portal/drivers'
      path: '/drivers'
      fullPath: '/portal/drivers'
      preLoaderRoute: typeof PortalDriversRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/fleet': {
      id: '/portal/fleet'
      path: '/fleet'
      fullPath: '/portal/fleet'
      preLoaderRoute: typeof PortalFleetRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/incidents': {
      id: '/portal/incidents'
      path: '/incidents'
      fullPath: '/portal/incidents'
      preLoaderRoute: typeof PortalIncidentsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/requests': {
      id: '/portal/requests'
      path: '/requests'
      fullPath: '/portal/requests'
      preLoaderRoute: typeof PortalRequestsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/routes-tracking': {
      id: '/portal/routes-tracking'
      path: '/routes-tracking'
      fullPath: '/portal/routes-tracking'
      preLoaderRoute: typeof PortalRoutesTrackingRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/sample-logistics': {
      id: '/portal/sample-logistics'
      path: '/sample-logistics'
      fullPath: '/portal/sample-logistics'
      preLoaderRoute: typeof PortalSampleLogisticsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/transactions': {
      id: '/portal/transactions'
      path: '/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof PortalTransactionsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/transport-requests': {
      id: '/portal/transport-requests'
      path: '/transport-requests'
      fullPath: '/portal/transport-requests'
      preLoaderRoute: typeof PortalTransportRequestsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/vehicles': {
      id: '/portal/vehicles'
      path: '/vehicles'
      fullPath: '/portal/vehicles'
      preLoaderRoute: typeof PortalVehiclesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/drivers_/$driverId': {
      id: '/portal/drivers_/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/portal/drivers/$driverId'
      preLoaderRoute: typeof PortalDriversDriverIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/movements/$movementId': {
      id: '/portal/movements/$movementId'
      path: '/movements/$movementId'
      fullPath: '/portal/movements/$movementId'
      preLoaderRoute: typeof PortalMovementsMovementIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/transactions_/$txnId': {
      id: '/portal/transactions_/$txnId'
      path: '/transactions/$txnId'
      fullPath: '/portal/transactions/$txnId'
      preLoaderRoute: typeof PortalTransactionsTxnIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/transport-requests_/$requestId': {
      id: '/portal/transport-requests_/$requestId'
      path: '/transport-requests/$requestId'
      fullPath: '/portal/transport-requests/$requestId'
      preLoaderRoute: typeof PortalTransportRequestsRequestIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/vehicles_/$vehicleId': {
      id: '/portal/vehicles_/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/portal/vehicles/$vehicleId'
      preLoaderRoute: typeof PortalVehiclesVehicleIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface PortalRouteRouteChildren {
  PortalActiveMovementsRoute: typeof PortalActiveMovementsRoute
  PortalApplicationRecordRoute: typeof PortalApplicationRecordRoute
  PortalBulkLogisticsRoute: typeof PortalBulkLogisticsRoute
  PortalComplianceRoute: typeof PortalComplianceRoute
  PortalDeliveriesRoute: typeof PortalDeliveriesRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalDriversRoute: typeof PortalDriversRoute
  PortalFleetRoute: typeof PortalFleetRoute
  PortalIncidentsRoute: typeof PortalIncidentsRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalRequestsRoute: typeof PortalRequestsRoute
  PortalRoutesTrackingRoute: typeof PortalRoutesTrackingRoute
  PortalSampleLogisticsRoute: typeof PortalSampleLogisticsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalTransactionsRoute: typeof PortalTransactionsRoute
  PortalTransportRequestsRoute: typeof PortalTransportRequestsRoute
  PortalVehiclesRoute: typeof PortalVehiclesRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalDriversDriverIdRoute: typeof PortalDriversDriverIdRoute
  PortalMovementsMovementIdRoute: typeof PortalMovementsMovementIdRoute
  PortalTransactionsTxnIdRoute: typeof PortalTransactionsTxnIdRoute
  PortalTransportRequestsRequestIdRoute: typeof PortalTransportRequestsRequestIdRoute
  PortalVehiclesVehicleIdRoute: typeof PortalVehiclesVehicleIdRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalActiveMovementsRoute: PortalActiveMovementsRoute,
  PortalApplicationRecordRoute: PortalApplicationRecordRoute,
  PortalBulkLogisticsRoute: PortalBulkLogisticsRoute,
  PortalComplianceRoute: PortalComplianceRoute,
  PortalDeliveriesRoute: PortalDeliveriesRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalDriversRoute: PortalDriversRoute,
  PortalFleetRoute: PortalFleetRoute,
  PortalIncidentsRoute: PortalIncidentsRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalRequestsRoute: PortalRequestsRoute,
  PortalRoutesTrackingRoute: PortalRoutesTrackingRoute,
  PortalSampleLogisticsRoute: PortalSampleLogisticsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalTransactionsRoute: PortalTransactionsRoute,
  PortalTransportRequestsRoute: PortalTransportRequestsRoute,
  PortalVehiclesRoute: PortalVehiclesRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalDriversDriverIdRoute: PortalDriversDriverIdRoute,
  PortalMovementsMovementIdRoute: PortalMovementsMovementIdRoute,
  PortalTransactionsTxnIdRoute: PortalTransactionsTxnIdRoute,
  PortalTransportRequestsRequestIdRoute: PortalTransportRequestsRequestIdRoute,
  PortalVehiclesVehicleIdRoute: PortalVehiclesVehicleIdRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  ApplicationRoute: ApplicationRoute,
  AuthRoute: AuthRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  SubmittedRoute: SubmittedRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
