/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NonconformitiesRouteImport } from './routes/nonconformities'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as ApplicationsIdRouteImport } from './routes/applications.$id'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as CertificatesIdRouteImport } from './routes/certificates.$id'
import { Route as SamplesIndexRouteImport } from './routes/samples.index'
import { Route as SamplesIdRouteImport } from './routes/samples.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NonconformitiesRoute = NonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIdRoute = CertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIndexRoute = SamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIdRoute = SamplesIdRouteImport.update({
  id: '/samples/$id',
  path: '/samples/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/nonconformities': typeof NonconformitiesRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/samples/$id': typeof SamplesIdRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/samples/': typeof SamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/nonconformities': typeof NonconformitiesRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/samples/$id': typeof SamplesIdRoute
  '/applications': typeof ApplicationsIndexRoute
  '/certificates': typeof CertificatesIndexRoute
  '/samples': typeof SamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/nonconformities': typeof NonconformitiesRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/samples/$id': typeof SamplesIdRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/samples/': typeof SamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/nonconformities'
    | '/applications/$id'
    | '/certificates/$id'
    | '/samples/$id'
    | '/applications/'
    | '/certificates/'
    | '/samples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/nonconformities'
    | '/applications/$id'
    | '/certificates/$id'
    | '/samples/$id'
    | '/applications'
    | '/certificates'
    | '/samples'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dashboard'
    | '/nonconformities'
    | '/applications/$id'
    | '/certificates/$id'
    | '/samples/$id'
    | '/applications/'
    | '/certificates/'
    | '/samples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  NonconformitiesRoute: typeof NonconformitiesRoute
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  CertificatesIdRoute: typeof CertificatesIdRoute
  SamplesIdRoute: typeof SamplesIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  SamplesIndexRoute: typeof SamplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nonconformities': {
      id: '/nonconformities'
      path: '/nonconformities'
      fullPath: '/nonconformities'
      preLoaderRoute: typeof NonconformitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$id': {
      id: '/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof CertificatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/': {
      id: '/samples/'
      path: '/samples'
      fullPath: '/samples/'
      preLoaderRoute: typeof SamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$id': {
      id: '/samples/$id'
      path: '/samples/$id'
      fullPath: '/samples/$id'
      preLoaderRoute: typeof SamplesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  NonconformitiesRoute: NonconformitiesRoute,
  ApplicationsIdRoute: ApplicationsIdRoute,
  CertificatesIdRoute: CertificatesIdRoute,
  SamplesIdRoute: SamplesIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  SamplesIndexRoute: SamplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
