/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as OperatorDocumentsRouteImport } from './routes/operator.documents'
import { Route as OperatorFacilityRouteImport } from './routes/operator.facility'
import { Route as OperatorIncidentsRouteImport } from './routes/operator.incidents'
import { Route as OperatorInventoryRouteImport } from './routes/operator.inventory'
import { Route as OperatorLocationsRouteImport } from './routes/operator.locations'
import { Route as OperatorReceiveRouteImport } from './routes/operator.receive'
import { Route as OperatorReleasesRouteImport } from './routes/operator.releases'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerAlertsRouteImport } from './routes/partner.alerts'
import { Route as PartnerAuditRouteImport } from './routes/partner.audit'
import { Route as PartnerFacilitiesRouteImport } from './routes/partner.facilities'
import { Route as PartnerInspectionsRouteImport } from './routes/partner.inspections'
import { Route as PartnerNonConformitiesRouteImport } from './routes/partner.non-conformities'
import { Route as RegulatorIndexRouteImport } from './routes/regulator.index'
import { Route as RegulatorCertificatesRouteImport } from './routes/regulator.certificates'
import { Route as RegulatorFacilitiesRouteImport } from './routes/regulator.facilities'
import { Route as RegulatorIncidentsRouteImport } from './routes/regulator.incidents'
import { Route as RegulatorInspectionsRouteImport } from './routes/regulator.inspections'
import { Route as RegulatorReportsRouteImport } from './routes/regulator.reports'
import { Route as PartnerApplicationsIndexRouteImport } from './routes/partner.applications.index'
import { Route as PartnerApplicationsIdRouteImport } from './routes/partner.applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorDocumentsRoute = OperatorDocumentsRouteImport.update({
  id: '/operator/documents',
  path: '/operator/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorFacilityRoute = OperatorFacilityRouteImport.update({
  id: '/operator/facility',
  path: '/operator/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIncidentsRoute = OperatorIncidentsRouteImport.update({
  id: '/operator/incidents',
  path: '/operator/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorInventoryRoute = OperatorInventoryRouteImport.update({
  id: '/operator/inventory',
  path: '/operator/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorLocationsRoute = OperatorLocationsRouteImport.update({
  id: '/operator/locations',
  path: '/operator/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorReceiveRoute = OperatorReceiveRouteImport.update({
  id: '/operator/receive',
  path: '/operator/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorReleasesRoute = OperatorReleasesRouteImport.update({
  id: '/operator/releases',
  path: '/operator/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAlertsRoute = PartnerAlertsRouteImport.update({
  id: '/partner/alerts',
  path: '/partner/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAuditRoute = PartnerAuditRouteImport.update({
  id: '/partner/audit',
  path: '/partner/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerFacilitiesRoute = PartnerFacilitiesRouteImport.update({
  id: '/partner/facilities',
  path: '/partner/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerInspectionsRoute = PartnerInspectionsRouteImport.update({
  id: '/partner/inspections',
  path: '/partner/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerNonConformitiesRoute = PartnerNonConformitiesRouteImport.update({
  id: '/partner/non-conformities',
  path: '/partner/non-conformities',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorIndexRoute = RegulatorIndexRouteImport.update({
  id: '/regulator/',
  path: '/regulator/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorCertificatesRoute = RegulatorCertificatesRouteImport.update({
  id: '/regulator/certificates',
  path: '/regulator/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorFacilitiesRoute = RegulatorFacilitiesRouteImport.update({
  id: '/regulator/facilities',
  path: '/regulator/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorIncidentsRoute = RegulatorIncidentsRouteImport.update({
  id: '/regulator/incidents',
  path: '/regulator/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorInspectionsRoute = RegulatorInspectionsRouteImport.update({
  id: '/regulator/inspections',
  path: '/regulator/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorReportsRoute = RegulatorReportsRouteImport.update({
  id: '/regulator/reports',
  path: '/regulator/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplicationsIndexRoute =
  PartnerApplicationsIndexRouteImport.update({
    id: '/partner/applications/',
    path: '/partner/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnerApplicationsIdRoute = PartnerApplicationsIdRouteImport.update({
  id: '/partner/applications/$id',
  path: '/partner/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/facility': typeof OperatorFacilityRoute
  '/operator/incidents': typeof OperatorIncidentsRoute
  '/operator/inventory': typeof OperatorInventoryRoute
  '/operator/locations': typeof OperatorLocationsRoute
  '/operator/receive': typeof OperatorReceiveRoute
  '/operator/releases': typeof OperatorReleasesRoute
  '/partner/alerts': typeof PartnerAlertsRoute
  '/partner/audit': typeof PartnerAuditRoute
  '/partner/facilities': typeof PartnerFacilitiesRoute
  '/partner/inspections': typeof PartnerInspectionsRoute
  '/partner/non-conformities': typeof PartnerNonConformitiesRoute
  '/regulator/certificates': typeof RegulatorCertificatesRoute
  '/regulator/facilities': typeof RegulatorFacilitiesRoute
  '/regulator/incidents': typeof RegulatorIncidentsRoute
  '/regulator/inspections': typeof RegulatorInspectionsRoute
  '/regulator/reports': typeof RegulatorReportsRoute
  '/operator/': typeof OperatorIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/regulator/': typeof RegulatorIndexRoute
  '/partner/applications/$id': typeof PartnerApplicationsIdRoute
  '/partner/applications/': typeof PartnerApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/facility': typeof OperatorFacilityRoute
  '/operator/incidents': typeof OperatorIncidentsRoute
  '/operator/inventory': typeof OperatorInventoryRoute
  '/operator/locations': typeof OperatorLocationsRoute
  '/operator/receive': typeof OperatorReceiveRoute
  '/operator/releases': typeof OperatorReleasesRoute
  '/partner/alerts': typeof PartnerAlertsRoute
  '/partner/audit': typeof PartnerAuditRoute
  '/partner/facilities': typeof PartnerFacilitiesRoute
  '/partner/inspections': typeof PartnerInspectionsRoute
  '/partner/non-conformities': typeof PartnerNonConformitiesRoute
  '/regulator/certificates': typeof RegulatorCertificatesRoute
  '/regulator/facilities': typeof RegulatorFacilitiesRoute
  '/regulator/incidents': typeof RegulatorIncidentsRoute
  '/regulator/inspections': typeof RegulatorInspectionsRoute
  '/regulator/reports': typeof RegulatorReportsRoute
  '/operator': typeof OperatorIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/regulator': typeof RegulatorIndexRoute
  '/partner/applications/$id': typeof PartnerApplicationsIdRoute
  '/partner/applications': typeof PartnerApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/facility': typeof OperatorFacilityRoute
  '/operator/incidents': typeof OperatorIncidentsRoute
  '/operator/inventory': typeof OperatorInventoryRoute
  '/operator/locations': typeof OperatorLocationsRoute
  '/operator/receive': typeof OperatorReceiveRoute
  '/operator/releases': typeof OperatorReleasesRoute
  '/partner/alerts': typeof PartnerAlertsRoute
  '/partner/audit': typeof PartnerAuditRoute
  '/partner/facilities': typeof PartnerFacilitiesRoute
  '/partner/inspections': typeof PartnerInspectionsRoute
  '/partner/non-conformities': typeof PartnerNonConformitiesRoute
  '/regulator/certificates': typeof RegulatorCertificatesRoute
  '/regulator/facilities': typeof RegulatorFacilitiesRoute
  '/regulator/incidents': typeof RegulatorIncidentsRoute
  '/regulator/inspections': typeof RegulatorInspectionsRoute
  '/regulator/reports': typeof RegulatorReportsRoute
  '/operator/': typeof OperatorIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/regulator/': typeof RegulatorIndexRoute
  '/partner/applications/$id': typeof PartnerApplicationsIdRoute
  '/partner/applications/': typeof PartnerApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/operator/documents'
    | '/operator/facility'
    | '/operator/incidents'
    | '/operator/inventory'
    | '/operator/locations'
    | '/operator/receive'
    | '/operator/releases'
    | '/partner/alerts'
    | '/partner/audit'
    | '/partner/facilities'
    | '/partner/inspections'
    | '/partner/non-conformities'
    | '/regulator/certificates'
    | '/regulator/facilities'
    | '/regulator/incidents'
    | '/regulator/inspections'
    | '/regulator/reports'
    | '/operator/'
    | '/partner/'
    | '/regulator/'
    | '/partner/applications/$id'
    | '/partner/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/operator/documents'
    | '/operator/facility'
    | '/operator/incidents'
    | '/operator/inventory'
    | '/operator/locations'
    | '/operator/receive'
    | '/operator/releases'
    | '/partner/alerts'
    | '/partner/audit'
    | '/partner/facilities'
    | '/partner/inspections'
    | '/partner/non-conformities'
    | '/regulator/certificates'
    | '/regulator/facilities'
    | '/regulator/incidents'
    | '/regulator/inspections'
    | '/regulator/reports'
    | '/operator'
    | '/partner'
    | '/regulator'
    | '/partner/applications/$id'
    | '/partner/applications'
  id:
    | '__root__'
    | '/'
    | '/operator/documents'
    | '/operator/facility'
    | '/operator/incidents'
    | '/operator/inventory'
    | '/operator/locations'
    | '/operator/receive'
    | '/operator/releases'
    | '/partner/alerts'
    | '/partner/audit'
    | '/partner/facilities'
    | '/partner/inspections'
    | '/partner/non-conformities'
    | '/regulator/certificates'
    | '/regulator/facilities'
    | '/regulator/incidents'
    | '/regulator/inspections'
    | '/regulator/reports'
    | '/operator/'
    | '/partner/'
    | '/regulator/'
    | '/partner/applications/$id'
    | '/partner/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OperatorDocumentsRoute: typeof OperatorDocumentsRoute
  OperatorFacilityRoute: typeof OperatorFacilityRoute
  OperatorIncidentsRoute: typeof OperatorIncidentsRoute
  OperatorInventoryRoute: typeof OperatorInventoryRoute
  OperatorLocationsRoute: typeof OperatorLocationsRoute
  OperatorReceiveRoute: typeof OperatorReceiveRoute
  OperatorReleasesRoute: typeof OperatorReleasesRoute
  PartnerAlertsRoute: typeof PartnerAlertsRoute
  PartnerAuditRoute: typeof PartnerAuditRoute
  PartnerFacilitiesRoute: typeof PartnerFacilitiesRoute
  PartnerInspectionsRoute: typeof PartnerInspectionsRoute
  PartnerNonConformitiesRoute: typeof PartnerNonConformitiesRoute
  RegulatorCertificatesRoute: typeof RegulatorCertificatesRoute
  RegulatorFacilitiesRoute: typeof RegulatorFacilitiesRoute
  RegulatorIncidentsRoute: typeof RegulatorIncidentsRoute
  RegulatorInspectionsRoute: typeof RegulatorInspectionsRoute
  RegulatorReportsRoute: typeof RegulatorReportsRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  RegulatorIndexRoute: typeof RegulatorIndexRoute
  PartnerApplicationsIdRoute: typeof PartnerApplicationsIdRoute
  PartnerApplicationsIndexRoute: typeof PartnerApplicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/documents': {
      id: '/operator/documents'
      path: '/operator/documents'
      fullPath: '/operator/documents'
      preLoaderRoute: typeof OperatorDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/facility': {
      id: '/operator/facility'
      path: '/operator/facility'
      fullPath: '/operator/facility'
      preLoaderRoute: typeof OperatorFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/incidents': {
      id: '/operator/incidents'
      path: '/operator/incidents'
      fullPath: '/operator/incidents'
      preLoaderRoute: typeof OperatorIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/inventory': {
      id: '/operator/inventory'
      path: '/operator/inventory'
      fullPath: '/operator/inventory'
      preLoaderRoute: typeof OperatorInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/locations': {
      id: '/operator/locations'
      path: '/operator/locations'
      fullPath: '/operator/locations'
      preLoaderRoute: typeof OperatorLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/receive': {
      id: '/operator/receive'
      path: '/operator/receive'
      fullPath: '/operator/receive'
      preLoaderRoute: typeof OperatorReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/releases': {
      id: '/operator/releases'
      path: '/operator/releases'
      fullPath: '/operator/releases'
      preLoaderRoute: typeof OperatorReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/alerts': {
      id: '/partner/alerts'
      path: '/partner/alerts'
      fullPath: '/partner/alerts'
      preLoaderRoute: typeof PartnerAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/audit': {
      id: '/partner/audit'
      path: '/partner/audit'
      fullPath: '/partner/audit'
      preLoaderRoute: typeof PartnerAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/facilities': {
      id: '/partner/facilities'
      path: '/partner/facilities'
      fullPath: '/partner/facilities'
      preLoaderRoute: typeof PartnerFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/inspections': {
      id: '/partner/inspections'
      path: '/partner/inspections'
      fullPath: '/partner/inspections'
      preLoaderRoute: typeof PartnerInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/non-conformities': {
      id: '/partner/non-conformities'
      path: '/partner/non-conformities'
      fullPath: '/partner/non-conformities'
      preLoaderRoute: typeof PartnerNonConformitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/': {
      id: '/regulator/'
      path: '/regulator'
      fullPath: '/regulator/'
      preLoaderRoute: typeof RegulatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/certificates': {
      id: '/regulator/certificates'
      path: '/regulator/certificates'
      fullPath: '/regulator/certificates'
      preLoaderRoute: typeof RegulatorCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/facilities': {
      id: '/regulator/facilities'
      path: '/regulator/facilities'
      fullPath: '/regulator/facilities'
      preLoaderRoute: typeof RegulatorFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/incidents': {
      id: '/regulator/incidents'
      path: '/regulator/incidents'
      fullPath: '/regulator/incidents'
      preLoaderRoute: typeof RegulatorIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/inspections': {
      id: '/regulator/inspections'
      path: '/regulator/inspections'
      fullPath: '/regulator/inspections'
      preLoaderRoute: typeof RegulatorInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/reports': {
      id: '/regulator/reports'
      path: '/regulator/reports'
      fullPath: '/regulator/reports'
      preLoaderRoute: typeof RegulatorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/applications/': {
      id: '/partner/applications/'
      path: '/partner/applications'
      fullPath: '/partner/applications/'
      preLoaderRoute: typeof PartnerApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/applications/$id': {
      id: '/partner/applications/$id'
      path: '/partner/applications/$id'
      fullPath: '/partner/applications/$id'
      preLoaderRoute: typeof PartnerApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OperatorDocumentsRoute: OperatorDocumentsRoute,
  OperatorFacilityRoute: OperatorFacilityRoute,
  OperatorIncidentsRoute: OperatorIncidentsRoute,
  OperatorInventoryRoute: OperatorInventoryRoute,
  OperatorLocationsRoute: OperatorLocationsRoute,
  OperatorReceiveRoute: OperatorReceiveRoute,
  OperatorReleasesRoute: OperatorReleasesRoute,
  PartnerAlertsRoute: PartnerAlertsRoute,
  PartnerAuditRoute: PartnerAuditRoute,
  PartnerFacilitiesRoute: PartnerFacilitiesRoute,
  PartnerInspectionsRoute: PartnerInspectionsRoute,
  PartnerNonConformitiesRoute: PartnerNonConformitiesRoute,
  RegulatorCertificatesRoute: RegulatorCertificatesRoute,
  RegulatorFacilitiesRoute: RegulatorFacilitiesRoute,
  RegulatorIncidentsRoute: RegulatorIncidentsRoute,
  RegulatorInspectionsRoute: RegulatorInspectionsRoute,
  RegulatorReportsRoute: RegulatorReportsRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  RegulatorIndexRoute: RegulatorIndexRoute,
  PartnerApplicationsIdRoute: PartnerApplicationsIdRoute,
  PartnerApplicationsIndexRoute: PartnerApplicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
