import type {
  ActivityEntry,
  Application,
  DocumentRecord,
  EnvRecord,
  Equipment,
  Inspection,
  LicenceDoc,
  MineSite,
  NonConformity,
  Organisation,
  PendingReview,
  ReviewSection,
  Sample,
  SafetyIncident,
} from "./types";

export const DEMO_TODAY = "2026-08-23";

export const organisations: Organisation[] = [
  {
    id: "org-nlm",
    name: "Nasarawa Lithium Minerals Ltd",
    rcNumber: "RC-1428903",
    type: "Private Limited Company",
    hq: "Plot 14, Jos Road, Lafia, Nasarawa State",
    contact: "Ibrahim Danladi",
    email: "compliance@nasarawalithium.ng",
    phone: "+234 803 441 2290",
    onboarded: "2023-04-11",
    status: "Under Review",
    complianceScore: 74,
    risk: "Medium",
    siteCount: 3,
    directors: [
      { name: "Ibrahim Danladi", role: "Managing Director", bvnVerified: true, nationality: "Nigerian" },
      { name: "Ngozi Ekwueme", role: "Finance Director", bvnVerified: true, nationality: "Nigerian" },
      { name: "Wei Zhang", role: "Technical Director", bvnVerified: false, nationality: "Chinese" },
    ],
    beneficialOwners: [
      { name: "Ibrahim Danladi", stake: 45, pepScreened: true, country: "Nigeria" },
      { name: "Sunrise Minerals Holding Ltd", stake: 40, pepScreened: false, country: "Hong Kong" },
      { name: "Ngozi Ekwueme", stake: 15, pepScreened: true, country: "Nigeria" },
    ],
  },
  {
    id: "org-kmr",
    name: "Kogi Mineral Resources Plc",
    rcNumber: "RC-0928144",
    type: "Public Limited Company",
    hq: "12 Murtala Way, Lokoja, Kogi State",
    contact: "Abiola Fasheun",
    email: "regulatory@kogimineral.ng",
    phone: "+234 811 220 7781",
    onboarded: "2021-09-02",
    status: "Active",
    complianceScore: 88,
    risk: "Low",
    siteCount: 2,
    directors: [
      { name: "Abiola Fasheun", role: "Chief Executive", bvnVerified: true, nationality: "Nigerian" },
      { name: "Samuel Ochai", role: "Operations Director", bvnVerified: true, nationality: "Nigerian" },
    ],
    beneficialOwners: [
      { name: "Kogi State Investment Corp", stake: 51, pepScreened: true, country: "Nigeria" },
      { name: "Abiola Fasheun", stake: 24, pepScreened: true, country: "Nigeria" },
      { name: "Free float", stake: 25, pepScreened: true, country: "Nigeria" },
    ],
  },
  {
    id: "org-omc",
    name: "Oyo Mineral Concessions Ltd",
    rcNumber: "RC-1730557",
    type: "Private Limited Company",
    hq: "5 Ring Road, Ibadan, Oyo State",
    contact: "Folake Adeyemi",
    email: "hse@oyoconcessions.ng",
    phone: "+234 807 998 3312",
    onboarded: "2024-01-19",
    status: "Active",
    complianceScore: 66,
    risk: "Medium",
    siteCount: 2,
    directors: [
      { name: "Folake Adeyemi", role: "Managing Director", bvnVerified: true, nationality: "Nigerian" },
      { name: "Peter Oyelaran", role: "Mine Manager", bvnVerified: true, nationality: "Nigerian" },
    ],
    beneficialOwners: [
      { name: "Folake Adeyemi", stake: 60, pepScreened: true, country: "Nigeria" },
      { name: "Adeyemi Family Trust", stake: 40, pepScreened: true, country: "Nigeria" },
    ],
  },
  {
    id: "org-ked",
    name: "Kaduna Exploration & Development",
    rcNumber: "RC-1109876",
    type: "Private Limited Company",
    hq: "Independence Way, Kaduna",
    contact: "Musa Bello",
    email: "info@kadunaexplore.ng",
    phone: "+234 802 771 4409",
    onboarded: "2022-06-30",
    status: "Suspended",
    complianceScore: 41,
    risk: "High",
    siteCount: 1,
    directors: [{ name: "Musa Bello", role: "Managing Director", bvnVerified: false, nationality: "Nigerian" }],
    beneficialOwners: [{ name: "Musa Bello", stake: 100, pepScreened: false, country: "Nigeria" }],
  },
];

const nl024Sections: ReviewSection[] = [
  {
    key: "corporate",
    title: "Corporate",
    summary: "Company registration, tax status and statutory filings.",
    weight: 10,
    score: 88,
    status: "Verified",
    fields: [
      { label: "Registered name", value: "Nasarawa Lithium Minerals Ltd", flag: "ok" },
      { label: "RC number", value: "RC-1428903", flag: "ok" },
      { label: "TIN", value: "20948113-0001", flag: "ok" },
      { label: "CAC annual return", value: "Filed 2026-03-14", flag: "ok" },
      { label: "Tax clearance", value: "Valid to 2026-12-31", flag: "ok" },
      { label: "MCO registration", value: "MCO/NAS/2023/0412", flag: "ok" },
    ],
    evidence: [
      { id: "ev-c1", name: "CAC Certificate of Incorporation.pdf", kind: "PDF", uploaded: "2026-02-02", size: "1.2 MB", status: "Verified" },
      { id: "ev-c2", name: "Tax Clearance Certificate 2026.pdf", kind: "Certificate", uploaded: "2026-02-02", size: "640 KB", status: "Verified" },
      { id: "ev-c3", name: "CAC Annual Return 2026.pdf", kind: "PDF", uploaded: "2026-03-15", size: "890 KB", status: "Verified" },
    ],
  },
  {
    key: "licence",
    title: "Licence",
    summary: "Mining lease validity, fees and conditions of grant.",
    weight: 15,
    score: 71,
    status: "Pending",
    fields: [
      { label: "Licence number", value: "ML-24187-NAS", flag: "ok" },
      { label: "Licence type", value: "Small Scale Mining Lease", flag: "ok" },
      { label: "Issued", value: "2023-05-02", flag: "ok" },
      { label: "Expiry", value: "2026-11-30", flag: "warn", note: "Expires in 99 days: renewal not yet filed." },
      { label: "Annual service fee", value: "Paid 2026-01-18", flag: "ok" },
      { label: "Community Development Agreement", value: "Draft under negotiation", flag: "warn", note: "CDA required within 6 months of grant." },
    ],
    evidence: [
      { id: "ev-l1", name: "Mining Lease ML-24187-NAS.pdf", kind: "Certificate", uploaded: "2026-01-20", size: "2.4 MB", status: "Verified" },
      { id: "ev-l2", name: "Annual Service Fee Receipt.pdf", kind: "PDF", uploaded: "2026-01-19", size: "310 KB", status: "Verified" },
      { id: "ev-l3", name: "Draft Community Development Agreement.pdf", kind: "PDF", uploaded: "2026-06-04", size: "1.1 MB", status: "Pending" },
    ],
  },
  {
    key: "site",
    title: "Site & GPS",
    summary: "Cadastral boundary, coordinates and encroachment checks.",
    weight: 10,
    score: 82,
    status: "Pending",
    fields: [
      { label: "Cadastral unit", value: "NAS/CU/44821", flag: "ok" },
      { label: "Centroid", value: "8.5412° N, 8.3157° E", flag: "ok" },
      { label: "Licensed area", value: "112.4 ha", flag: "ok" },
      { label: "Surveyed area", value: "118.9 ha", flag: "warn", note: "6.5 ha of activity observed outside cadastral boundary." },
      { label: "Buffer to settlement", value: "740 m (Angwan Doka)", flag: "ok" },
      { label: "Protected area overlap", value: "None detected", flag: "ok" },
    ],
    evidence: [
      { id: "ev-s1", name: "Cadastral Survey Plan.pdf", kind: "PDF", uploaded: "2026-04-11", size: "3.8 MB", status: "Verified" },
      { id: "ev-s2", name: "Drone Boundary Overlay.png", kind: "Image", uploaded: "2026-07-22", size: "5.1 MB", status: "Pending" },
    ],
  },
  {
    key: "ownership",
    title: "Ownership",
    summary: "Directors, beneficial ownership and PEP/sanctions screening.",
    weight: 10,
    score: 64,
    status: "Pending",
    fields: [
      { label: "Directors on file", value: "3", flag: "ok" },
      { label: "BVN verification", value: "2 of 3 verified", flag: "warn", note: "Technical Director (foreign national) pending identity verification." },
      { label: "Beneficial owners declared", value: "3 (100% coverage)", flag: "ok" },
      { label: "PEP screening", value: "Sunrise Minerals Holding Ltd not screened", flag: "bad", note: "Offshore 40% holder requires enhanced due diligence." },
      { label: "Sanctions check", value: "Clear (last run 2026-08-01)", flag: "ok" },
    ],
    evidence: [
      { id: "ev-o1", name: "CAC Form CO7 - Directors.pdf", kind: "PDF", uploaded: "2026-02-02", size: "720 KB", status: "Verified" },
      { id: "ev-o2", name: "Beneficial Ownership Declaration.pdf", kind: "PDF", uploaded: "2026-02-02", size: "480 KB", status: "Pending" },
    ],
  },
  {
    key: "environmental",
    title: "Environmental",
    summary: "EIA approval, effluent quality, dust and rehabilitation bond.",
    weight: 15,
    score: 62,
    status: "Pending",
    fields: [
      { label: "EIA approval", value: "FMEnv/EIA/2023/1188", flag: "ok" },
      { label: "Environmental Protection & Rehabilitation Fund", value: "₦42.0m of ₦55.0m lodged", flag: "warn", note: "Shortfall of ₦13.0m against the approved rehabilitation estimate." },
      { label: "Turbidity: Doka Stream", value: "68 NTU (limit 50 NTU)", flag: "bad", note: "Exceedance recorded during July rains." },
      { label: "PM10 dust (perimeter)", value: "142 µg/m³ (limit 150)", flag: "warn" },
      { label: "Tailings storage", value: "Lined, freeboard 1.4 m", flag: "ok" },
      { label: "Progressive rehabilitation", value: "3.2 ha of 9.0 ha disturbed", flag: "warn" },
    ],
    evidence: [
      { id: "ev-e1", name: "EIA Approval Certificate.pdf", kind: "Certificate", uploaded: "2026-01-20", size: "1.9 MB", status: "Verified" },
      { id: "ev-e2", name: "Q2 2026 Water Quality Report.pdf", kind: "Report", uploaded: "2026-07-14", size: "2.2 MB", status: "Pending" },
      { id: "ev-e3", name: "Rehabilitation Bond Statement.pdf", kind: "PDF", uploaded: "2026-06-30", size: "540 KB", status: "Pending" },
    ],
  },
  {
    key: "safety",
    title: "Safety",
    summary: "Incident history, LTIFR, training records and PPE compliance.",
    weight: 10,
    score: 70,
    status: "Pending",
    fields: [
      { label: "LTIFR (12 months)", value: "3.4 per million hours", flag: "warn", note: "Sector benchmark 2.1." },
      { label: "Lost-time incidents", value: "2 in last 12 months", flag: "warn" },
      { label: "Mine safety officer", value: "Appointed: Sadiq Umaru (Cert. MSO/1188)", flag: "ok" },
      { label: "Emergency response drill", value: "Last held 2026-05-09", flag: "ok" },
      { label: "PPE compliance audit", value: "84% conformance", flag: "warn" },
      { label: "Explosives handling", value: "Not applicable: no blasting licence", flag: "ok" },
    ],
    evidence: [
      { id: "ev-sa1", name: "Safety Management Plan v3.pdf", kind: "PDF", uploaded: "2026-03-02", size: "3.4 MB", status: "Verified" },
      { id: "ev-sa2", name: "Incident Register H1 2026.xlsx", kind: "Spreadsheet", uploaded: "2026-07-05", size: "220 KB", status: "Pending" },
    ],
  },
  {
    key: "equipment",
    title: "Equipment",
    summary: "Plant register, certification and maintenance status.",
    weight: 8,
    score: 78,
    status: "Pending",
    fields: [
      { label: "Registered plant items", value: "14", flag: "ok" },
      { label: "Certified & in date", value: "11 of 14", flag: "warn", note: "2 items overdue for statutory inspection." },
      { label: "Weighbridge calibration", value: "Valid to 2026-10-04", flag: "ok" },
      { label: "Crusher throughput", value: "35 t/h rated", flag: "ok" },
      { label: "Generator emissions test", value: "Overdue since 2026-06-15", flag: "bad" },
    ],
    evidence: [
      { id: "ev-eq1", name: "Plant & Equipment Register.xlsx", kind: "Spreadsheet", uploaded: "2026-07-01", size: "180 KB", status: "Verified" },
      { id: "ev-eq2", name: "Weighbridge Calibration Certificate.pdf", kind: "Certificate", uploaded: "2026-04-06", size: "410 KB", status: "Verified" },
    ],
  },
  {
    key: "production",
    title: "Production",
    summary: "Declared output, royalties and reconciliation against despatch.",
    weight: 12,
    score: 76,
    status: "Pending",
    fields: [
      { label: "Declared output YTD", value: "18,420 t spodumene ore", flag: "ok" },
      { label: "Despatch records", value: "18,065 t", flag: "warn", note: "355 t variance (1.9%) unreconciled." },
      { label: "Royalty paid YTD", value: "₦96.4m", flag: "ok" },
      { label: "Licensed capacity", value: "36,000 t/yr", flag: "ok" },
      { label: "Utilisation", value: "78% of capacity", flag: "ok" },
      { label: "Monthly returns", value: "July 2026 return submitted late (12 days)", flag: "warn" },
    ],
    evidence: [
      { id: "ev-p1", name: "Monthly Production Return July 2026.pdf", kind: "PDF", uploaded: "2026-08-12", size: "760 KB", status: "Pending" },
      { id: "ev-p2", name: "Royalty Payment Evidence Q2.pdf", kind: "PDF", uploaded: "2026-07-08", size: "520 KB", status: "Verified" },
    ],
  },
  {
    key: "sampling",
    title: "Sampling & Quality",
    summary: "Sample chain of custody and accredited laboratory results.",
    weight: 5,
    score: 85,
    status: "Pending",
    fields: [
      { label: "Samples submitted (12 mo)", value: "24", flag: "ok" },
      { label: "Accredited laboratory", value: "SGS Nigeria, Ibadan (ISO 17025)", flag: "ok" },
      { label: "Mean Li₂O grade", value: "1.42%", flag: "ok" },
      { label: "Grade variance vs declaration", value: "-0.08 pp", flag: "ok" },
      { label: "Chain-of-custody gaps", value: "1 sample (SMP-2026-019)", flag: "warn" },
    ],
    evidence: [
      { id: "ev-q1", name: "SGS Certificate SGS-NG-114872.pdf", kind: "Certificate", uploaded: "2026-08-05", size: "980 KB", status: "Verified" },
      { id: "ev-q2", name: "Chain of Custody Log.pdf", kind: "PDF", uploaded: "2026-08-05", size: "340 KB", status: "Pending" },
    ],
  },
  {
    key: "inspection",
    title: "Inspection",
    summary: "Site inspection history, findings and close-out evidence.",
    weight: 5,
    score: 68,
    status: "Pending",
    fields: [
      { label: "Last inspection", value: "2026-06-18 (Routine)", flag: "ok" },
      { label: "Result", value: "Pass with Observations", flag: "warn" },
      { label: "Open findings", value: "2 of 5", flag: "warn" },
      { label: "Next scheduled", value: "2026-09-15", flag: "ok" },
      { label: "Inspector access", value: "Granted without restriction", flag: "ok" },
    ],
    evidence: [
      { id: "ev-i1", name: "Inspection Report INS-2026-0341.pdf", kind: "Report", uploaded: "2026-06-24", size: "4.1 MB", status: "Verified" },
      { id: "ev-i2", name: "Close-out Photos June 2026.png", kind: "Image", uploaded: "2026-07-02", size: "6.4 MB", status: "Pending" },
    ],
  },
];

function genericSections(bias: number): ReviewSection[] {
  return nl024Sections.map((s) => ({
    ...s,
    score: Math.max(30, Math.min(98, s.score + bias)),
    status: "Pending" as const,
    evidence: s.evidence.map((e) => ({ ...e, id: `${e.id}-${bias}` })),
  }));
}

export const sites: MineSite[] = [
  {
    id: "NL-024",
    code: "NL-024",
    name: "Nasarawa Lithium Site NL-024",
    orgId: "org-nlm",
    mineral: "Lithium (Spodumene)",
    state: "Nasarawa",
    lga: "Kokona",
    lat: 8.5412,
    lng: 8.3157,
    areaHa: 112.4,
    licenceId: "lic-ml24187",
    status: "Under Review",
    complianceScore: 74,
    risk: "Medium",
    capacityTpa: 36000,
    currentTpa: 28080,
    workforce: 142,
    lastInspection: "2026-06-18",
    verification: { site: true, licence: true, documents: false, gps: false },
    scoreFactors: [
      { id: "f1", label: "Licence & permits", weight: 15, score: 71, reason: "Lease valid but expires in 99 days with no renewal filed; CDA still in draft.", trend: "down" },
      { id: "f2", label: "Environmental performance", weight: 15, score: 62, reason: "Turbidity exceedance at Doka Stream (68 NTU vs 50 NTU limit) and a ₦13.0m rehabilitation bond shortfall.", trend: "down" },
      { id: "f3", label: "Production & royalty integrity", weight: 12, score: 76, reason: "355 t (1.9%) variance between declared output and despatch; July return filed 12 days late.", trend: "flat" },
      { id: "f4", label: "Corporate standing", weight: 10, score: 88, reason: "CAC filings, TIN and tax clearance all current and verified.", trend: "up" },
      { id: "f5", label: "Ownership transparency", weight: 10, score: 64, reason: "Offshore 40% beneficial owner has not completed PEP screening; one director lacks identity verification.", trend: "flat" },
      { id: "f6", label: "Site & boundary integrity", weight: 10, score: 82, reason: "6.5 ha of activity observed outside the cadastral boundary on July drone overlay.", trend: "down" },
      { id: "f7", label: "Safety performance", weight: 10, score: 70, reason: "LTIFR of 3.4 against sector benchmark 2.1; PPE conformance at 84%.", trend: "flat" },
      { id: "f8", label: "Equipment certification", weight: 8, score: 78, reason: "11 of 14 plant items in certification date; generator emissions test overdue.", trend: "flat" },
      { id: "f9", label: "Inspection close-out", weight: 5, score: 68, reason: "2 of 5 findings from the June routine inspection remain open past their close-out date.", trend: "down" },
      { id: "f10", label: "Sampling & assay quality", weight: 5, score: 85, reason: "ISO 17025 lab used throughout; a single chain-of-custody gap on SMP-2026-019.", trend: "up" },
    ],
    riskReasons: [
      "Environmental exceedance is active and unresolved (turbidity 36% above the permitted limit).",
      "Mining lease expires within 100 days with no renewal application on file.",
      "Beneficial ownership is only 60% screened, the offshore holder triggers enhanced due diligence.",
      "Production-to-despatch variance of 1.9% is above the 1.0% reconciliation tolerance.",
      "Mitigating: corporate standing, royalty payments and assay quality are all strong, keeping the profile out of the High band.",
    ],
    sections: nl024Sections,
    production: [
      { month: "Feb", tonnes: 2180, grade: 1.38 },
      { month: "Mar", tonnes: 2460, grade: 1.44 },
      { month: "Apr", tonnes: 2710, grade: 1.41 },
      { month: "May", tonnes: 2890, grade: 1.47 },
      { month: "Jun", tonnes: 2640, grade: 1.4 },
      { month: "Jul", tonnes: 2350, grade: 1.36 },
      { month: "Aug", tonnes: 1890, grade: 1.43 },
    ],
    inventory: [
      { item: "Run-of-mine spodumene ore", qty: "4,120 t", location: "ROM Pad A", updated: "2026-08-21" },
      { item: "Crushed ore (−25 mm)", qty: "1,860 t", location: "Stockpile B", updated: "2026-08-20" },
      { item: "Concentrate awaiting despatch", qty: "640 t", location: "Bagging Shed", updated: "2026-08-22" },
      { item: "Waste rock", qty: "12,400 t", location: "Dump 2", updated: "2026-08-18" },
    ],
    transactions: [
      { id: "TRX-4411", date: "2026-08-14", buyer: "Lagos Battery Materials Ltd", tonnes: 620, value: "₦188.4m", status: "Cleared" },
      { id: "TRX-4390", date: "2026-07-28", buyer: "Sinoma Trading (export)", tonnes: 1100, value: "₦341.0m", status: "Cleared" },
      { id: "TRX-4372", date: "2026-07-09", buyer: "Lagos Battery Materials Ltd", tonnes: 580, value: "₦174.9m", status: "Under Query" },
    ],
  },
  {
    id: "NL-031",
    code: "NL-031",
    name: "Kokona Ridge Pegmatite NL-031",
    orgId: "org-nlm",
    mineral: "Lithium (Lepidolite)",
    state: "Nasarawa",
    lga: "Kokona",
    lat: 8.6021,
    lng: 8.2711,
    areaHa: 78.2,
    licenceId: "lic-ml24512",
    status: "Operational",
    complianceScore: 81,
    risk: "Low",
    capacityTpa: 18000,
    currentTpa: 12600,
    workforce: 64,
    lastInspection: "2026-05-04",
    verification: { site: true, licence: true, documents: true, gps: true },
    scoreFactors: [],
    riskReasons: ["All statutory returns current; no open findings."],
    sections: genericSections(7),
    production: [
      { month: "Feb", tonnes: 980, grade: 1.12 },
      { month: "Mar", tonnes: 1050, grade: 1.16 },
      { month: "Apr", tonnes: 1120, grade: 1.14 },
      { month: "May", tonnes: 1090, grade: 1.19 },
      { month: "Jun", tonnes: 1180, grade: 1.21 },
      { month: "Jul", tonnes: 1140, grade: 1.18 },
      { month: "Aug", tonnes: 870, grade: 1.15 },
    ],
    inventory: [{ item: "Run-of-mine ore", qty: "1,940 t", location: "ROM Pad", updated: "2026-08-19" }],
    transactions: [{ id: "TRX-4402", date: "2026-08-06", buyer: "Abuja Ceramics Ltd", tonnes: 310, value: "₦64.2m", status: "Cleared" }],
  },
  {
    id: "NL-009",
    code: "NL-009",
    name: "Doka Alluvial Workings NL-009",
    orgId: "org-nlm",
    mineral: "Lithium (Alluvial)",
    state: "Nasarawa",
    lga: "Karu",
    lat: 8.9114,
    lng: 7.7402,
    areaHa: 41.7,
    licenceId: "lic-ml23990",
    status: "Care & Maintenance",
    complianceScore: 58,
    risk: "High",
    capacityTpa: 9000,
    currentTpa: 1200,
    workforce: 18,
    lastInspection: "2026-02-27",
    verification: { site: true, licence: false, documents: false, gps: true },
    scoreFactors: [],
    riskReasons: ["Licence lapsed pending renewal.", "Rehabilitation plan overdue by 4 months."],
    sections: genericSections(-16),
    production: [
      { month: "Feb", tonnes: 210, grade: 0.94 },
      { month: "Mar", tonnes: 160, grade: 0.91 },
      { month: "Apr", tonnes: 120, grade: 0.9 },
      { month: "May", tonnes: 90, grade: 0.88 },
      { month: "Jun", tonnes: 0, grade: 0 },
      { month: "Jul", tonnes: 0, grade: 0 },
      { month: "Aug", tonnes: 0, grade: 0 },
    ],
    inventory: [{ item: "Residual stockpile", qty: "310 t", location: "Pad C", updated: "2026-06-02" }],
    transactions: [],
  },
  {
    id: "KG-112",
    code: "KG-112",
    name: "Lokoja Lithium Prospect KG-112",
    orgId: "org-kmr",
    mineral: "Lithium (Spodumene)",
    state: "Kogi",
    lga: "Lokoja",
    lat: 7.8023,
    lng: 6.7333,
    areaHa: 204.6,
    licenceId: "lic-ml22014",
    status: "Operational",
    complianceScore: 91,
    risk: "Low",
    capacityTpa: 54000,
    currentTpa: 47500,
    workforce: 268,
    lastInspection: "2026-07-30",
    verification: { site: true, licence: true, documents: true, gps: true },
    scoreFactors: [],
    riskReasons: ["Consistently compliant across all sections."],
    sections: genericSections(14),
    production: [
      { month: "Feb", tonnes: 3820, grade: 1.51 },
      { month: "Mar", tonnes: 4020, grade: 1.55 },
      { month: "Apr", tonnes: 4180, grade: 1.53 },
      { month: "May", tonnes: 4210, grade: 1.58 },
      { month: "Jun", tonnes: 4090, grade: 1.54 },
      { month: "Jul", tonnes: 4150, grade: 1.56 },
      { month: "Aug", tonnes: 3110, grade: 1.52 },
    ],
    inventory: [{ item: "Concentrate", qty: "2,410 t", location: "Warehouse 1", updated: "2026-08-22" }],
    transactions: [{ id: "TRX-4415", date: "2026-08-18", buyer: "Sinoma Trading (export)", tonnes: 1800, value: "₦602.7m", status: "Cleared" }],
  },
  {
    id: "KG-118",
    code: "KG-118",
    name: "Adankolo Tin-Lithium KG-118",
    orgId: "org-kmr",
    mineral: "Lithium / Cassiterite",
    state: "Kogi",
    lga: "Lokoja",
    lat: 7.7541,
    lng: 6.6902,
    areaHa: 96.1,
    licenceId: "lic-ml22770",
    status: "Operational",
    complianceScore: 84,
    risk: "Low",
    capacityTpa: 21000,
    currentTpa: 16400,
    workforce: 97,
    lastInspection: "2026-04-16",
    verification: { site: true, licence: true, documents: true, gps: true },
    scoreFactors: [],
    riskReasons: ["Minor documentation lag only."],
    sections: genericSections(9),
    production: [
      { month: "Feb", tonnes: 1320, grade: 1.22 },
      { month: "Mar", tonnes: 1410, grade: 1.25 },
      { month: "Apr", tonnes: 1380, grade: 1.2 },
      { month: "May", tonnes: 1450, grade: 1.27 },
      { month: "Jun", tonnes: 1390, grade: 1.24 },
      { month: "Jul", tonnes: 1420, grade: 1.26 },
      { month: "Aug", tonnes: 1010, grade: 1.23 },
    ],
    inventory: [{ item: "ROM ore", qty: "880 t", location: "Pad A", updated: "2026-08-17" }],
    transactions: [],
  },
  {
    id: "OY-046",
    code: "OY-046",
    name: "Oke-Ogun Pegmatite OY-046",
    orgId: "org-omc",
    mineral: "Lithium (Pegmatite)",
    state: "Oyo",
    lga: "Iseyin",
    lat: 7.9702,
    lng: 3.5981,
    areaHa: 64.3,
    licenceId: "lic-ml25001",
    status: "Under Review",
    complianceScore: 66,
    risk: "Medium",
    capacityTpa: 14000,
    currentTpa: 9100,
    workforce: 58,
    lastInspection: "2026-03-11",
    verification: { site: true, licence: true, documents: false, gps: true },
    scoreFactors: [],
    riskReasons: ["Dust monitoring records incomplete.", "Two safety findings past close-out date."],
    sections: genericSections(-8),
    production: [
      { month: "Feb", tonnes: 740, grade: 1.05 },
      { month: "Mar", tonnes: 810, grade: 1.08 },
      { month: "Apr", tonnes: 790, grade: 1.02 },
      { month: "May", tonnes: 840, grade: 1.1 },
      { month: "Jun", tonnes: 720, grade: 1.04 },
      { month: "Jul", tonnes: 690, grade: 1.01 },
      { month: "Aug", tonnes: 520, grade: 1.06 },
    ],
    inventory: [{ item: "ROM ore", qty: "620 t", location: "ROM Pad", updated: "2026-08-15" }],
    transactions: [],
  },
  {
    id: "OY-052",
    code: "OY-052",
    name: "Iseyin North Extension OY-052",
    orgId: "org-omc",
    mineral: "Lithium (Pegmatite)",
    state: "Oyo",
    lga: "Iseyin",
    lat: 8.0244,
    lng: 3.5612,
    areaHa: 52.8,
    licenceId: "lic-ml25040",
    status: "Operational",
    complianceScore: 72,
    risk: "Medium",
    capacityTpa: 11000,
    currentTpa: 6800,
    workforce: 41,
    lastInspection: "2026-06-02",
    verification: { site: true, licence: true, documents: true, gps: false },
    scoreFactors: [],
    riskReasons: ["GPS boundary re-survey outstanding."],
    sections: genericSections(-2),
    production: [
      { month: "Feb", tonnes: 520, grade: 0.98 },
      { month: "Mar", tonnes: 560, grade: 1.01 },
      { month: "Apr", tonnes: 610, grade: 1.03 },
      { month: "May", tonnes: 590, grade: 0.99 },
      { month: "Jun", tonnes: 620, grade: 1.04 },
      { month: "Jul", tonnes: 580, grade: 1.0 },
      { month: "Aug", tonnes: 430, grade: 1.02 },
    ],
    inventory: [],
    transactions: [],
  },
  {
    id: "KD-077",
    code: "KD-077",
    name: "Birnin Gwari Workings KD-077",
    orgId: "org-ked",
    mineral: "Lithium (Alluvial)",
    state: "Kaduna",
    lga: "Birnin Gwari",
    lat: 10.6612,
    lng: 6.5433,
    areaHa: 33.5,
    licenceId: "lic-ml21008",
    status: "Suspended",
    complianceScore: 41,
    risk: "High",
    capacityTpa: 7000,
    currentTpa: 0,
    workforce: 0,
    lastInspection: "2026-01-22",
    verification: { site: false, licence: false, documents: false, gps: false },
    scoreFactors: [],
    riskReasons: ["Operating licence suspended following unresolved critical non-conformity.", "No environmental returns filed in 2026."],
    sections: genericSections(-30),
    production: [
      { month: "Feb", tonnes: 0, grade: 0 },
      { month: "Mar", tonnes: 0, grade: 0 },
      { month: "Apr", tonnes: 0, grade: 0 },
      { month: "May", tonnes: 0, grade: 0 },
      { month: "Jun", tonnes: 0, grade: 0 },
      { month: "Jul", tonnes: 0, grade: 0 },
      { month: "Aug", tonnes: 0, grade: 0 },
    ],
    inventory: [],
    transactions: [],
  },
];

export const licences: LicenceDoc[] = [
  { id: "lic-ml24187", number: "ML-24187-NAS", type: "Small Scale Mining Lease", siteId: "NL-024", orgId: "org-nlm", issued: "2023-05-02", expiry: "2026-11-30", status: "Expiring", authority: "Mining Cadastre Office" },
  { id: "lic-ml24512", number: "ML-24512-NAS", type: "Small Scale Mining Lease", siteId: "NL-031", orgId: "org-nlm", issued: "2023-09-14", expiry: "2028-09-13", status: "Active", authority: "Mining Cadastre Office" },
  { id: "lic-ml23990", number: "ML-23990-NAS", type: "Quarry Lease", siteId: "NL-009", orgId: "org-nlm", issued: "2022-03-01", expiry: "2026-03-01", status: "Expired", authority: "Mining Cadastre Office" },
  { id: "lic-ml22014", number: "ML-22014-KOG", type: "Mining Lease", siteId: "KG-112", orgId: "org-kmr", issued: "2021-11-04", expiry: "2031-11-03", status: "Active", authority: "Mining Cadastre Office" },
  { id: "lic-ml22770", number: "ML-22770-KOG", type: "Small Scale Mining Lease", siteId: "KG-118", orgId: "org-kmr", issued: "2022-02-18", expiry: "2027-02-17", status: "Active", authority: "Mining Cadastre Office" },
  { id: "lic-ml25001", number: "ML-25001-OYO", type: "Small Scale Mining Lease", siteId: "OY-046", orgId: "org-omc", issued: "2024-02-20", expiry: "2026-10-19", status: "Expiring", authority: "Mining Cadastre Office" },
  { id: "lic-ml25040", number: "ML-25040-OYO", type: "Exploration Licence", siteId: "OY-052", orgId: "org-omc", issued: "2024-06-11", expiry: "2027-06-10", status: "Active", authority: "Mining Cadastre Office" },
  { id: "lic-ml21008", number: "ML-21008-KAD", type: "Small Scale Mining Lease", siteId: "KD-077", orgId: "org-ked", issued: "2021-04-09", expiry: "2026-04-08", status: "Suspended", authority: "Mining Cadastre Office" },
];

export const documents: DocumentRecord[] = [
  { id: "doc-1", name: "Mining Lease ML-24187-NAS", category: "Licence", siteId: "NL-024", uploaded: "2026-01-20", expiry: "2026-11-30", status: "Verified", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-2", name: "EIA Approval Certificate", category: "Environmental", siteId: "NL-024", uploaded: "2026-01-20", expiry: "2028-01-19", status: "Verified", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-3", name: "Q2 2026 Water Quality Report", category: "Environmental", siteId: "NL-024", uploaded: "2026-07-14", status: "Pending", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-4", name: "Rehabilitation Bond Statement", category: "Financial", siteId: "NL-024", uploaded: "2026-06-30", status: "Pending", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-5", name: "Beneficial Ownership Declaration", category: "Corporate", siteId: "NL-024", uploaded: "2026-02-02", status: "Pending", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-6", name: "Plant & Equipment Register", category: "Operations", siteId: "NL-024", uploaded: "2026-07-01", status: "Verified", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-7", name: "Generator Emissions Test", category: "Environmental", siteId: "NL-024", uploaded: "2025-06-15", expiry: "2026-06-15", status: "Expired", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-8", name: "Quarry Lease ML-23990-NAS", category: "Licence", siteId: "NL-009", uploaded: "2022-03-05", expiry: "2026-03-01", status: "Expired", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-9", name: "Dust Monitoring Log Q2", category: "Environmental", siteId: "OY-046", uploaded: "2026-07-19", status: "Rejected", owner: "Oyo Mineral Concessions Ltd" },
  { id: "doc-10", name: "Mining Lease ML-22014-KOG", category: "Licence", siteId: "KG-112", uploaded: "2021-11-08", expiry: "2031-11-03", status: "Verified", owner: "Kogi Mineral Resources Plc" },
  { id: "doc-11", name: "Safety Management Plan v3", category: "Safety", siteId: "NL-024", uploaded: "2026-03-02", status: "Verified", owner: "Nasarawa Lithium Minerals Ltd" },
  { id: "doc-12", name: "SGS Certificate SGS-NG-114872", category: "Quality", siteId: "NL-024", uploaded: "2026-08-05", status: "Verified", owner: "SGS Nigeria" },
];

export const applications: Application[] = [
  { id: "app-1", ref: "APP-2026-0412", orgId: "org-nlm", siteName: "Nasarawa Lithium Site NL-024", type: "Lease Renewal", mineral: "Lithium", submitted: "2026-08-12", stage: "Compliance Review", status: "Under Review", assignedTo: "A. Okonkwo", slaDays: 4 },
  { id: "app-2", ref: "APP-2026-0407", orgId: "org-omc", siteName: "Oke-Ogun Pegmatite OY-046", type: "Variation of Conditions", mineral: "Lithium", submitted: "2026-08-09", stage: "Document Verification", status: "Info Requested", assignedTo: "A. Okonkwo", slaDays: 1 },
  { id: "app-3", ref: "APP-2026-0399", orgId: "org-kmr", siteName: "Adankolo Tin-Lithium KG-118", type: "Capacity Increase", mineral: "Lithium / Cassiterite", submitted: "2026-08-04", stage: "Technical Assessment", status: "Under Review", assignedTo: "T. Bamidele", slaDays: 7 },
  { id: "app-4", ref: "APP-2026-0388", orgId: "org-nlm", siteName: "Kokona Ridge Pegmatite NL-031", type: "Export Permit", mineral: "Lithium", submitted: "2026-07-28", stage: "Approved", status: "Approved", assignedTo: "A. Okonkwo", slaDays: 0 },
  { id: "app-5", ref: "APP-2026-0376", orgId: "org-ked", siteName: "Birnin Gwari Workings KD-077", type: "Licence Reinstatement", mineral: "Lithium", submitted: "2026-07-19", stage: "Rejected", status: "Rejected", assignedTo: "T. Bamidele", slaDays: 0 },
  { id: "app-6", ref: "APP-2026-0421", orgId: "org-omc", siteName: "Iseyin North Extension OY-052", type: "New Site Registration", mineral: "Lithium", submitted: "2026-08-20", stage: "Intake", status: "Pending", assignedTo: "Unassigned", slaDays: 9 },
];

export const pendingReviews: PendingReview[] = [
  { id: "rev-1", siteId: "NL-024", subject: "Environmental exceedance evidence pack", type: "Environmental", priority: "High", submitted: "2026-08-18", due: "2026-08-25", status: "In Progress", assignedTo: "A. Okonkwo" },
  { id: "rev-2", siteId: "NL-024", subject: "Lease renewal supporting documents", type: "Licence", priority: "High", submitted: "2026-08-12", due: "2026-08-26", status: "Queued", assignedTo: "A. Okonkwo" },
  { id: "rev-3", siteId: "OY-046", subject: "Dust monitoring log resubmission", type: "Environmental", priority: "Normal", submitted: "2026-08-15", due: "2026-08-29", status: "Queued", assignedTo: "A. Okonkwo" },
  { id: "rev-4", siteId: "NL-009", subject: "Rehabilitation plan overdue", type: "Environmental", priority: "High", submitted: "2026-08-02", due: "2026-08-21", status: "Queued", assignedTo: "T. Bamidele" },
  { id: "rev-5", siteId: "KG-118", subject: "Capacity increase technical file", type: "Production", priority: "Normal", submitted: "2026-08-04", due: "2026-09-01", status: "Queued", assignedTo: "T. Bamidele" },
  { id: "rev-6", siteId: "OY-052", subject: "GPS boundary re-survey", type: "Site & GPS", priority: "Low", submitted: "2026-07-30", due: "2026-09-05", status: "Queued", assignedTo: "A. Okonkwo" },
  { id: "rev-7", siteId: "KD-077", subject: "Suspension appeal submission", type: "Corporate", priority: "High", submitted: "2026-08-11", due: "2026-08-24", status: "Queued", assignedTo: "T. Bamidele" },
];

export const inspections: Inspection[] = [
  {
    id: "ins-1",
    ref: "INS-2026-0341",
    siteId: "NL-024",
    type: "Routine Compliance Inspection",
    scheduled: "2026-06-18",
    inspector: "Engr. Sadiq Umaru",
    status: "Completed",
    result: "Pass with Observations",
    notes: "Site access granted without restriction. Housekeeping around the crusher has improved since the prior visit.",
    findings: [
      { id: "fnd-1", area: "Environmental", observation: "Silt trap upstream of Doka Stream at capacity; overflow observed after rainfall.", severity: "Major" },
      { id: "fnd-2", area: "Safety", observation: "PPE non-conformance among 4 contract haulage operators.", severity: "Minor" },
      { id: "fnd-3", area: "Equipment", observation: "Generator emissions test certificate expired.", severity: "Minor" },
      { id: "fnd-4", area: "Boundary", observation: "Excavation observed approximately 90 m beyond eastern cadastral peg.", severity: "Major" },
      { id: "fnd-5", area: "Records", observation: "Chain-of-custody form missing for sample SMP-2026-019.", severity: "Minor" },
    ],
  },
  { id: "ins-2", ref: "INS-2026-0402", siteId: "NL-024", type: "Follow-up Inspection", scheduled: "2026-09-15", inspector: "Engr. Sadiq Umaru", status: "Scheduled", findings: [] },
  { id: "ins-3", ref: "INS-2026-0377", siteId: "KG-112", type: "Routine Compliance Inspection", scheduled: "2026-07-30", inspector: "Mrs. Chinwe Obi", status: "Completed", result: "Pass", findings: [] },
  { id: "ins-4", ref: "INS-2026-0310", siteId: "OY-046", type: "Environmental Audit", scheduled: "2026-03-11", inspector: "Mrs. Chinwe Obi", status: "Completed", result: "Pass with Observations", findings: [{ id: "fnd-6", area: "Environmental", observation: "Dust suppression schedule not evidenced.", severity: "Minor" }] },
  { id: "ins-5", ref: "INS-2026-0290", siteId: "KD-077", type: "Enforcement Inspection", scheduled: "2026-01-22", inspector: "Engr. Sadiq Umaru", status: "Completed", result: "Fail", findings: [{ id: "fnd-7", area: "Licence", observation: "Operating without valid rehabilitation bond.", severity: "Critical" }] },
  { id: "ins-6", ref: "INS-2026-0415", siteId: "NL-009", type: "Care & Maintenance Verification", scheduled: "2026-08-30", inspector: "Mrs. Chinwe Obi", status: "Overdue", findings: [] },
];

export const samples: Sample[] = [
  { id: "smp-1", ref: "SMP-2026-024", siteId: "NL-024", collected: "2026-08-01", lab: "SGS Nigeria, Ibadan", certificate: "SGS-NG-114872", li2o: 1.46, fe2o3: 0.92, moisture: 4.1, status: "Verified", method: "ICP-OES (four-acid digest)", chainOfCustody: ["Collected by O. Yakubu (site geologist) 2026-08-01 09:12", "Sealed bag NL024-0801-A, tamper seal 88431", "Handover to courier 2026-08-01 14:40", "Received SGS Ibadan 2026-08-02 11:05", "Assay completed 2026-08-05"] },
  { id: "smp-2", ref: "SMP-2026-019", siteId: "NL-024", collected: "2026-06-22", lab: "SGS Nigeria, Ibadan", certificate: "SGS-NG-113998", li2o: 1.31, fe2o3: 1.14, moisture: 5.8, status: "Disputed", method: "ICP-OES (four-acid digest)", chainOfCustody: ["Collected by O. Yakubu 2026-06-22 08:40", "Chain-of-custody form missing between collection and courier handover", "Received SGS Ibadan 2026-06-25 10:20"] },
  { id: "smp-3", ref: "SMP-2026-022", siteId: "NL-024", collected: "2026-07-14", lab: "SGS Nigeria, Ibadan", certificate: "SGS-NG-114410", li2o: 1.39, fe2o3: 0.98, moisture: 4.6, status: "Verified", method: "ICP-OES (four-acid digest)", chainOfCustody: ["Collected 2026-07-14", "Received SGS Ibadan 2026-07-16", "Assay completed 2026-07-19"] },
  { id: "smp-4", ref: "SMP-2026-026", siteId: "KG-112", collected: "2026-08-10", lab: "Intertek Lagos", certificate: "ITK-NG-55210", li2o: 1.57, fe2o3: 0.81, moisture: 3.4, status: "Verified", method: "XRF + ICP confirmation", chainOfCustody: ["Collected 2026-08-10", "Received Intertek 2026-08-11"] },
  { id: "smp-5", ref: "SMP-2026-027", siteId: "OY-046", collected: "2026-08-16", lab: "Intertek Lagos", certificate: "Pending", li2o: 1.04, fe2o3: 1.32, moisture: 6.2, status: "Pending", method: "XRF screening", chainOfCustody: ["Collected 2026-08-16", "In transit"] },
];

export const envRecords: EnvRecord[] = [
  { id: "env-1", siteId: "NL-024", metric: "Turbidity: Doka Stream", value: "68 NTU", limit: "50 NTU", status: "Breach", measured: "2026-07-11" },
  { id: "env-2", siteId: "NL-024", metric: "PM10 dust (perimeter)", value: "142 µg/m³", limit: "150 µg/m³", status: "Watch", measured: "2026-08-02" },
  { id: "env-3", siteId: "NL-024", metric: "Noise (nearest receptor)", value: "58 dB(A)", limit: "65 dB(A)", status: "Within Limit", measured: "2026-08-02" },
  { id: "env-4", siteId: "NL-024", metric: "Rehabilitation progress", value: "3.2 ha", limit: "9.0 ha disturbed", status: "Watch", measured: "2026-06-30" },
  { id: "env-5", siteId: "OY-046", metric: "PM10 dust (perimeter)", value: "168 µg/m³", limit: "150 µg/m³", status: "Breach", measured: "2026-07-18" },
  { id: "env-6", siteId: "KG-112", metric: "Effluent pH", value: "7.2", limit: "6.5 – 8.5", status: "Within Limit", measured: "2026-08-05" },
  { id: "env-7", siteId: "KD-077", metric: "Rehabilitation bond", value: "₦0", limit: "₦18.0m", status: "Breach", measured: "2026-04-08" },
];

export const safetyIncidents: SafetyIncident[] = [
  { id: "saf-1", siteId: "NL-024", date: "2026-05-22", type: "Lost-time injury", severity: "Major", lostDays: 14, status: "Closed", summary: "Haulage operator sustained a hand injury during unguarded conveyor cleaning." },
  { id: "saf-2", siteId: "NL-024", date: "2026-02-08", type: "Lost-time injury", severity: "Minor", lostDays: 3, status: "Closed", summary: "Slip on wet ramp near the wash plant." },
  { id: "saf-3", siteId: "NL-024", date: "2026-08-04", type: "Near miss", severity: "Minor", lostDays: 0, status: "Investigating", summary: "Excavator swung within exclusion zone while a surveyor was present." },
  { id: "saf-4", siteId: "OY-046", date: "2026-06-19", type: "Lost-time injury", severity: "Major", lostDays: 9, status: "Investigating", summary: "Fall from height during screen maintenance without harness." },
  { id: "saf-5", siteId: "KD-077", date: "2025-12-02", type: "Fatality", severity: "Critical", lostDays: 0, status: "Closed", summary: "Pit wall collapse in unsupported alluvial working." },
];

export const equipment: Equipment[] = [
  { id: "eq-1", siteId: "NL-024", name: "Jaw crusher 35 t/h", serial: "JC-88214", certExpiry: "2027-01-14", status: "Certified" },
  { id: "eq-2", siteId: "NL-024", name: "Weighbridge 60 t", serial: "WB-4410", certExpiry: "2026-10-04", status: "Certified" },
  { id: "eq-3", siteId: "NL-024", name: "Excavator CAT 320", serial: "CAT-320-7712", certExpiry: "2026-09-01", status: "Due Inspection" },
  { id: "eq-4", siteId: "NL-024", name: "500 kVA generator", serial: "GEN-500-221", certExpiry: "2026-06-15", status: "Out of Service" },
  { id: "eq-5", siteId: "NL-024", name: "Haul truck fleet (6)", serial: "HT-FLEET-06", certExpiry: "2027-03-20", status: "Certified" },
  { id: "eq-6", siteId: "KG-112", name: "Dense media separator", serial: "DMS-1102", certExpiry: "2027-05-30", status: "Certified" },
];

export const nonConformities: NonConformity[] = [
  {
    id: "nc-1",
    ref: "NCR-2026-018",
    siteId: "NL-024",
    title: "Turbidity exceedance at Doka Stream discharge point",
    category: "Environmental",
    severity: "Major",
    requiredAction: "Install and commission secondary silt containment upstream of the discharge point, and submit two consecutive weeks of compliant turbidity readings from an accredited laboratory.",
    responsiblePerson: "Ibrahim Danladi (Managing Director)",
    deadline: "2026-09-12",
    raisedBy: "A. Okonkwo (Compliance Partner)",
    raisedAt: "2026-07-24",
    status: "Awaiting Review",
    submissions: [
      {
        id: "cs-1",
        at: "2026-08-19",
        by: "Ibrahim Danladi",
        message:
          "Secondary silt trap installed on 12 August and commissioned on 14 August. First week of post-installation sampling returned 41 NTU and 38 NTU. Second week of sampling is in progress and the certificate will follow on 26 August.",
        attachments: ["Silt trap commissioning photos.png", "Week 1 turbidity results (SGS).pdf"],
      },
    ],
  },
  {
    id: "nc-2",
    ref: "NCR-2026-021",
    siteId: "NL-024",
    title: "Generator emissions test certificate expired",
    category: "Equipment",
    severity: "Minor",
    requiredAction: "Complete a statutory emissions test for the 500 kVA generator and upload the valid certificate.",
    responsiblePerson: "Sadiq Umaru (Mine Safety Officer)",
    deadline: "2026-08-31",
    raisedBy: "A. Okonkwo (Compliance Partner)",
    raisedAt: "2026-08-01",
    status: "Open",
    submissions: [],
  },
  {
    id: "nc-3",
    ref: "NCR-2026-014",
    siteId: "NL-024",
    title: "Excavation beyond eastern cadastral boundary",
    category: "Site & GPS",
    severity: "Major",
    requiredAction: "Cease all activity east of peg E-04, commission an independent boundary re-survey and submit the surveyor's report.",
    responsiblePerson: "Peter Oyelaran (Mine Manager)",
    deadline: "2026-09-30",
    raisedBy: "T. Bamidele (Compliance Partner)",
    raisedAt: "2026-06-28",
    status: "In Progress",
    submissions: [],
  },
  {
    id: "nc-4",
    ref: "NCR-2026-009",
    siteId: "OY-046",
    title: "Dust suppression schedule not evidenced",
    category: "Environmental",
    severity: "Minor",
    requiredAction: "Submit signed daily dust suppression logs for the last quarter.",
    responsiblePerson: "Folake Adeyemi",
    deadline: "2026-08-20",
    raisedBy: "A. Okonkwo (Compliance Partner)",
    raisedAt: "2026-05-16",
    status: "Escalated",
    submissions: [],
  },
  {
    id: "nc-5",
    ref: "NCR-2025-044",
    siteId: "KD-077",
    title: "Operating without a valid rehabilitation bond",
    category: "Financial",
    severity: "Critical",
    requiredAction: "Lodge the full ₦18.0m rehabilitation bond before any resumption of operations.",
    responsiblePerson: "Musa Bello",
    deadline: "2026-03-31",
    raisedBy: "T. Bamidele (Compliance Partner)",
    raisedAt: "2025-12-18",
    status: "Escalated",
    submissions: [],
  },
  {
    id: "nc-6",
    ref: "NCR-2026-006",
    siteId: "NL-031",
    title: "Late submission of monthly production return",
    category: "Production",
    severity: "Minor",
    requiredAction: "Submit outstanding return and confirm the internal reporting calendar.",
    responsiblePerson: "Ngozi Ekwueme",
    deadline: "2026-04-15",
    raisedBy: "A. Okonkwo (Compliance Partner)",
    raisedAt: "2026-03-20",
    status: "Closed",
    submissions: [
      { id: "cs-2", at: "2026-04-10", by: "Ngozi Ekwueme", message: "Return submitted and reporting calendar circulated to all site leads.", attachments: ["March 2026 return.pdf"], decision: "Accepted", decisionNote: "Evidence sufficient. Closed.", decidedAt: "2026-04-12", decidedBy: "A. Okonkwo" },
    ],
  },
];

export const infoRequestsSeed = [
  {
    id: "ir-1",
    siteId: "NL-024",
    section: "ownership" as const,
    subject: "PEP screening for Sunrise Minerals Holding Ltd",
    details: "Provide certified beneficial ownership documentation and a completed PEP/sanctions screening for the 40% offshore holder.",
    requestedFrom: "Nasarawa Lithium Minerals Ltd",
    requestedBy: "A. Okonkwo",
    requestedAt: "2026-08-06",
    dueBy: "2026-08-27",
    priority: "High" as const,
    status: "Open" as const,
  },
];

export const activitySeed: ActivityEntry[] = [
  { id: "act-1", at: "2026-08-22 14:22", actor: "A. Okonkwo", role: "partner", action: "Opened review", detail: "Started compliance review of the environmental evidence pack.", target: "NL-024", tone: "neutral" },
  { id: "act-2", at: "2026-08-19 09:41", actor: "Ibrahim Danladi", role: "miner", action: "Corrective action submitted", detail: "Silt trap commissioning evidence uploaded against NCR-2026-018.", target: "NL-024", tone: "positive" },
  { id: "act-3", at: "2026-08-12 16:05", actor: "Nasarawa Lithium Minerals Ltd", role: "miner", action: "Application submitted", detail: "Lease renewal APP-2026-0412 filed for ML-24187-NAS.", target: "NL-024", tone: "neutral" },
  { id: "act-4", at: "2026-08-06 11:18", actor: "A. Okonkwo", role: "partner", action: "Information requested", detail: "PEP screening requested for Sunrise Minerals Holding Ltd.", target: "NL-024", tone: "warning" },
  { id: "act-5", at: "2026-08-01 08:30", actor: "A. Okonkwo", role: "partner", action: "Non-conformity raised", detail: "NCR-2026-021 raised for expired generator emissions certificate.", target: "NL-024", tone: "negative" },
  { id: "act-6", at: "2026-07-30 15:12", actor: "Mrs. Chinwe Obi", role: "partner", action: "Inspection completed", detail: "KG-112 routine inspection closed with a Pass result.", target: "KG-112", tone: "positive" },
  { id: "act-7", at: "2026-07-24 10:02", actor: "A. Okonkwo", role: "partner", action: "Non-conformity raised", detail: "NCR-2026-018 raised for turbidity exceedance at Doka Stream.", target: "NL-024", tone: "negative" },
  { id: "act-8", at: "2026-07-18 13:44", actor: "Federal Ministry (Oversight)", role: "regulator", action: "Reminder sent", detail: "Reminder issued to Oyo Mineral Concessions Ltd regarding dust monitoring logs.", target: "OY-046", tone: "warning" },
];

export const complianceTrend = [
  { month: "Feb", score: 68, inspections: 4, nonConformities: 9 },
  { month: "Mar", score: 70, inspections: 6, nonConformities: 8 },
  { month: "Apr", score: 72, inspections: 5, nonConformities: 7 },
  { month: "May", score: 71, inspections: 7, nonConformities: 9 },
  { month: "Jun", score: 74, inspections: 8, nonConformities: 6 },
  { month: "Jul", score: 73, inspections: 6, nonConformities: 8 },
  { month: "Aug", score: 76, inspections: 5, nonConformities: 6 },
];

export const users = {
  partner: { name: "Amaka Okonkwo", initials: "AO", title: "Mining Compliance Partner", org: "Beldium Compliance Services", shortName: "A. Okonkwo" },
  miner: { name: "Ibrahim Danladi", initials: "ID", title: "Managing Director", org: "Nasarawa Lithium Minerals Ltd", shortName: "I. Danladi" },
  regulator: { name: "Halima Yusuf", initials: "HY", title: "Regulatory Oversight Officer", org: "Federal Ministry of Solid Minerals Development", shortName: "H. Yusuf" },
} as const;

export const MINER_ORG_ID = "org-nlm";
export const MINER_PRIMARY_SITE = "NL-024";
