import type {
  Application,
  BuyerSpec,
  Certificate,
  DemoUser,
  NonConformity,
  Role,
  Sample,
} from "./types";

export const roleMeta: Record<
  Role,
  { label: string; tagline: string; color: string }
> = {
  operator: {
    label: "Compliance Operator",
    tagline: "Verifies Quality & Control Partners and owns the decision record",
    color: "navy",
  },
  partner: {
    label: "Quality Partner",
    tagline: "Accredited laboratory executing tests and issuing certificates",
    color: "blue",
  },
  miner: {
    label: "Miner / Producer",
    tagline: "Registers lots and samples, tracks custody to the lab",
    color: "amber",
  },
  buyer: {
    label: "Buyer",
    tagline: "Matches delivered material against purchase specifications",
    color: "mint",
  },
  regulator: {
    label: "Regulatory Oversight",
    tagline: "Read-only supervision of the traceability chain",
    color: "slate",
  },
};

export const demoUsers: DemoUser[] = [
  {
    id: "u-op",
    role: "operator",
    name: "Amina Delacroix",
    title: "Quality Officer, Level 2",
    org: "Beldium Compliance Authority",
    initials: "AD",
    blurb: "Full verification powers: approve, request info, reject, raise NCRs.",
  },
  {
    id: "u-pa",
    role: "partner",
    name: "Dr. Léon Mbaye",
    title: "Technical Manager",
    org: "Antwerp Assay Laboratories NV",
    initials: "LM",
    blurb: "Manage test requests, enter results, submit certificates.",
  },
  {
    id: "u-mi",
    role: "miner",
    name: "Grace Tumaini",
    title: "Site Compliance Lead",
    org: "Kivu Ridge Minerals",
    initials: "GT",
    blurb: "Register samples, hand over custody, follow lot status.",
  },
  {
    id: "u-bu",
    role: "buyer",
    name: "Hendrik Vos",
    title: "Raw Materials Procurement",
    org: "Vos Refining Group",
    initials: "HV",
    blurb: "Review spec matching, certificates and incoming lot trust.",
  },
  {
    id: "u-re",
    role: "regulator",
    name: "Inspector Claire Boone",
    title: "Federal Minerals Inspectorate",
    org: "Ministry of Economic Affairs",
    initials: "CB",
    blurb: "Read-only oversight across partners, chains and certificates.",
  },
];

const now = "2026-08-21";

export const applications: Application[] = [
  {
    id: "app-1",
    ref: "QCP-2026-0148",
    submittedAt: "2026-08-11",
    status: "in_review",
    assignedTo: "Amina Delacroix",
    riskScore: 62,
    organisation: {
      legalName: "Antwerp Assay Laboratories NV",
      tradingName: "AAL Assay",
      registrationNo: "BE 0742.118.904",
      country: "Belgium",
      city: "Antwerp",
      incorporated: "2011-03-04",
      website: "aal-assay.be",
      beneficialOwners: [
        { name: "Léon Mbaye", share: 46, pep: false },
        { name: "Stichting Kempen Holding", share: 54, pep: true },
      ],
      contact: {
        name: "Dr. Léon Mbaye",
        email: "l.mbaye@aal-assay.be",
        phone: "+32 3 555 0142",
      },
    },
    capability: {
      leadAssessor: "Dr. Léon Mbaye",
      credential: "EurGeol / ISO 17025 Lead Assessor",
      yearsExperience: 17,
      registry: "European Federation of Geologists",
      registryId: "EFG-1188-BE",
      staff: [
        { name: "Ilse Maes", role: "Analytical Chemist", competency: "ICP-MS, XRF", verified: true },
        { name: "Karel Op de Beeck", role: "Sample Custodian", competency: "Chain of custody", verified: true },
        { name: "Nadia Farouk", role: "Assayer", competency: "Fire assay", verified: false },
      ],
    },
    laboratory: {
      facility: "Antwerp Haven Lab, Unit 14",
      accreditation: "ISO/IEC 17025:2017",
      accreditationBody: "BELAC",
      certificateNo: "BELAC 268-TEST",
      validUntil: "2027-02-28",
      lastSurveillance: "2026-01-19",
      proficiencyTesting: "Round 2026-A: satisfactory (z = 0.8)",
      scope: [
        { method: "ICP-MS", matrix: "Cassiterite concentrate", analyte: "Sn, Ta, Nb", loq: "0.5 ppm", accredited: true },
        { method: "Fire assay / AAS", matrix: "Gold doré", analyte: "Au, Ag", loq: "0.01 g/t", accredited: true },
        { method: "XRF", matrix: "Coltan", analyte: "Ta2O5", loq: "50 ppm", accredited: true },
        { method: "LA-ICP-MS fingerprint", matrix: "Ore", analyte: "Trace origin profile", loq: "n/a", accredited: false },
      ],
    },
    documents: [
      { id: "d1", name: "Certificate of incorporation", category: "organisation", reference: "KBO-0742118904", issuer: "Belgian Crossroads Bank", issued: "2011-03-04", expires: null, status: "verified" },
      { id: "d2", name: "UBO register extract", category: "organisation", reference: "UBO-2026-33110", issuer: "FPS Finance", issued: "2026-06-02", expires: "2027-06-02", status: "pending", note: "Holding entity lists a politically exposed trustee." },
      { id: "d3", name: "Lead assessor credential", category: "professional", reference: "EFG-1188-BE", issuer: "EFG", issued: "2019-09-12", expires: "2027-09-12", status: "verified" },
      { id: "d4", name: "Assayer competency records", category: "professional", reference: "HR-CMP-114", issuer: "AAL Assay", issued: "2025-11-30", expires: null, status: "flagged", note: "Nadia Farouk fire-assay sign-off missing." },
      { id: "d5", name: "ISO/IEC 17025 accreditation certificate", category: "laboratory", reference: "BELAC 268-TEST", issuer: "BELAC", issued: "2023-03-01", expires: "2027-02-28", status: "verified" },
      { id: "d6", name: "Accredited scope annex", category: "laboratory", reference: "268-TEST/A7", issuer: "BELAC", issued: "2026-01-19", expires: "2027-02-28", status: "pending", note: "Fingerprint method claimed but outside annex." },
      { id: "d7", name: "Proficiency testing report", category: "laboratory", reference: "PT-2026-A", issuer: "IAG", issued: "2026-04-04", expires: null, status: "verified" },
      { id: "d8", name: "Conflict-minerals due diligence policy", category: "conditional", reference: "POL-CM-04", issuer: "AAL Assay", issued: "2026-02-10", expires: null, status: "pending", conditionalOn: "Scope includes 3TG material" },
      { id: "d9", name: "Export handling permit (3TG)", category: "conditional", reference: "EXP-3TG-8871", issuer: "Flemish Government", issued: "2024-05-20", expires: "2026-05-20", status: "expired", conditionalOn: "Scope includes 3TG material", note: "Renewal not on file." },
    ],
    riskFlags: [
      { id: "rf1", severity: "high", title: "Expired 3TG export permit", detail: "Conditional permit lapsed 2026-05-20 while the declared scope covers cassiterite and coltan.", resolved: false },
      { id: "rf2", severity: "medium", title: "PEP in ownership chain", detail: "Stichting Kempen Holding trustee appears on the national PEP list.", resolved: false },
      { id: "rf3", severity: "low", title: "Scope overreach", detail: "LA-ICP-MS fingerprinting advertised but not in the BELAC annex.", resolved: false },
    ],
    audit: [
      { id: "a1", at: "2026-08-11 09:12", actor: "Dr. Léon Mbaye", role: "partner", action: "Application submitted", detail: "9 documents attached" },
      { id: "a2", at: "2026-08-12 14:03", actor: "System", role: "operator", action: "Risk screening completed", detail: "3 flags raised, score 62" },
      { id: "a3", at: "2026-08-14 08:41", actor: "Amina Delacroix", role: "operator", action: "Review opened", detail: "Assigned to Quality Officer L2" },
    ],
  },
  {
    id: "app-2",
    ref: "QCP-2026-0151",
    submittedAt: "2026-08-15",
    status: "submitted",
    assignedTo: "Unassigned",
    riskScore: 24,
    organisation: {
      legalName: "Kigali Metallurgical Services Ltd",
      tradingName: "KMS Labs",
      registrationNo: "RW 108-442-991",
      country: "Rwanda",
      city: "Kigali",
      incorporated: "2017-08-22",
      website: "kmslabs.rw",
      beneficialOwners: [{ name: "Eric Nsengimana", share: 100, pep: false }],
      contact: { name: "Eric Nsengimana", email: "eric@kmslabs.rw", phone: "+250 788 220 114" },
    },
    capability: {
      leadAssessor: "Eric Nsengimana",
      credential: "MSc Metallurgy, ISO 17025 internal auditor",
      yearsExperience: 11,
      registry: "Rwanda Mining Association",
      registryId: "RMA-4471",
      staff: [
        { name: "Solange Uwase", role: "Analytical Chemist", competency: "XRF", verified: true },
        { name: "Patrick Habimana", role: "Sample Custodian", competency: "Chain of custody", verified: true },
      ],
    },
    laboratory: {
      facility: "Gasabo Industrial Park, Block C",
      accreditation: "ISO/IEC 17025:2017",
      accreditationBody: "SADCAS",
      certificateNo: "SADCAS TEST-119",
      validUntil: "2028-06-30",
      lastSurveillance: "2026-05-11",
      proficiencyTesting: "Round 2026-A: satisfactory (z = 1.4)",
      scope: [
        { method: "XRF", matrix: "Coltan", analyte: "Ta2O5, Nb2O5", loq: "80 ppm", accredited: true },
        { method: "ICP-OES", matrix: "Cassiterite", analyte: "Sn", loq: "1 ppm", accredited: true },
      ],
    },
    documents: [
      { id: "d1", name: "Certificate of incorporation", category: "organisation", reference: "RDB-108442991", issuer: "Rwanda Development Board", issued: "2017-08-22", expires: null, status: "pending" },
      { id: "d2", name: "Beneficial ownership declaration", category: "organisation", reference: "BO-2026-88", issuer: "KMS Labs", issued: "2026-07-01", expires: null, status: "pending" },
      { id: "d3", name: "Lead assessor credential", category: "professional", reference: "RMA-4471", issuer: "Rwanda Mining Association", issued: "2021-04-08", expires: "2027-04-08", status: "pending" },
      { id: "d4", name: "SADCAS accreditation certificate", category: "laboratory", reference: "TEST-119", issuer: "SADCAS", issued: "2024-07-01", expires: "2028-06-30", status: "pending" },
      { id: "d5", name: "Accredited scope annex", category: "laboratory", reference: "TEST-119/A2", issuer: "SADCAS", issued: "2026-05-11", expires: "2028-06-30", status: "pending" },
      { id: "d6", name: "Regional conflict-affected sourcing policy", category: "conditional", reference: "POL-CAHRA-1", issuer: "KMS Labs", issued: "2026-03-15", expires: null, status: "pending", conditionalOn: "Facility located in a CAHRA region" },
    ],
    riskFlags: [
      { id: "rf4", severity: "medium", title: "CAHRA jurisdiction", detail: "Facility operates in a conflict-affected and high-risk area; enhanced due diligence required.", resolved: false },
    ],
    audit: [
      { id: "a1", at: "2026-08-15 11:20", actor: "Eric Nsengimana", role: "partner", action: "Application submitted", detail: "6 documents attached" },
    ],
  },
  {
    id: "app-3",
    ref: "QCP-2026-0132",
    submittedAt: "2026-07-28",
    status: "info_requested",
    assignedTo: "Amina Delacroix",
    riskScore: 48,
    organisation: {
      legalName: "Nordic Ore Verification AB",
      tradingName: "NOV",
      registrationNo: "SE 559211-4478",
      country: "Sweden",
      city: "Luleå",
      incorporated: "2015-01-15",
      website: "nordicore.se",
      beneficialOwners: [
        { name: "Anna Lindqvist", share: 60, pep: false },
        { name: "Boreal Capital AB", share: 40, pep: false },
      ],
      contact: { name: "Anna Lindqvist", email: "anna@nordicore.se", phone: "+46 920 44 11 02" },
    },
    capability: {
      leadAssessor: "Anna Lindqvist",
      credential: "PhD Geochemistry",
      yearsExperience: 14,
      registry: "Swedish Geotechnical Society",
      registryId: "SGF-2210",
      staff: [{ name: "Olof Berg", role: "Assayer", competency: "Fire assay", verified: true }],
    },
    laboratory: {
      facility: "Luleå Science Park",
      accreditation: "ISO/IEC 17025:2017",
      accreditationBody: "SWEDAC",
      certificateNo: "SWEDAC 1774",
      validUntil: "2026-11-30",
      lastSurveillance: "2025-10-02",
      proficiencyTesting: "Round 2025-B: questionable (z = 2.4)",
      scope: [
        { method: "ICP-MS", matrix: "Iron ore", analyte: "Fe, P, S", loq: "0.2 ppm", accredited: true },
      ],
    },
    documents: [
      { id: "d1", name: "Certificate of incorporation", category: "organisation", reference: "SE5592114478", issuer: "Bolagsverket", issued: "2015-01-15", expires: null, status: "verified" },
      { id: "d2", name: "Lead assessor credential", category: "professional", reference: "SGF-2210", issuer: "SGF", issued: "2018-06-01", expires: "2028-06-01", status: "verified" },
      { id: "d3", name: "SWEDAC accreditation certificate", category: "laboratory", reference: "1774", issuer: "SWEDAC", issued: "2022-12-01", expires: "2026-11-30", status: "flagged", note: "Expires within 120 days; renewal evidence requested." },
      { id: "d4", name: "Proficiency testing report", category: "laboratory", reference: "PT-2025-B", issuer: "IAG", issued: "2025-12-11", expires: null, status: "flagged", note: "Questionable z-score, corrective evidence requested." },
    ],
    riskFlags: [
      { id: "rf5", severity: "medium", title: "Proficiency deviation", detail: "z = 2.4 on iron ore phosphorus round; retest evidence outstanding.", resolved: false },
      { id: "rf6", severity: "medium", title: "Accreditation expiring", detail: "SWEDAC certificate lapses 2026-11-30.", resolved: false },
    ],
    audit: [
      { id: "a1", at: "2026-07-28 10:00", actor: "Anna Lindqvist", role: "partner", action: "Application submitted", detail: "4 documents attached" },
      { id: "a2", at: "2026-08-02 16:22", actor: "Amina Delacroix", role: "operator", action: "Information requested", detail: "Renewal plan and PT corrective action requested" },
    ],
  },
  {
    id: "app-4",
    ref: "QCP-2026-0119",
    submittedAt: "2026-06-30",
    status: "approved",
    assignedTo: "Amina Delacroix",
    riskScore: 12,
    organisation: {
      legalName: "Pacific Metals Assay Pte Ltd",
      tradingName: "PMA",
      registrationNo: "SG 201644771H",
      country: "Singapore",
      city: "Jurong",
      incorporated: "2016-11-02",
      website: "pma-assay.sg",
      beneficialOwners: [{ name: "Wei Ling Tan", share: 100, pep: false }],
      contact: { name: "Wei Ling Tan", email: "wl.tan@pma-assay.sg", phone: "+65 6222 4410" },
    },
    capability: {
      leadAssessor: "Wei Ling Tan",
      credential: "Chartered Chemist, ISO 17025 Lead Assessor",
      yearsExperience: 21,
      registry: "Singapore Chemical Institute",
      registryId: "SCI-0912",
      staff: [{ name: "Rajesh Kumar", role: "Analytical Chemist", competency: "ICP-MS", verified: true }],
    },
    laboratory: {
      facility: "Jurong Assay Centre",
      accreditation: "ISO/IEC 17025:2017",
      accreditationBody: "SAC-SINGLAS",
      certificateNo: "SAC LA-0441",
      validUntil: "2029-01-31",
      lastSurveillance: "2026-02-14",
      proficiencyTesting: "Round 2026-A: satisfactory (z = 0.3)",
      scope: [
        { method: "ICP-MS", matrix: "Tin concentrate", analyte: "Sn, Pb, As", loq: "0.3 ppm", accredited: true },
        { method: "Fire assay", matrix: "Gold doré", analyte: "Au", loq: "0.01 g/t", accredited: true },
      ],
    },
    documents: [
      { id: "d1", name: "Certificate of incorporation", category: "organisation", reference: "201644771H", issuer: "ACRA", issued: "2016-11-02", expires: null, status: "verified" },
      { id: "d2", name: "Lead assessor credential", category: "professional", reference: "SCI-0912", issuer: "SCI", issued: "2017-01-01", expires: "2027-01-01", status: "verified" },
      { id: "d3", name: "SAC-SINGLAS accreditation", category: "laboratory", reference: "LA-0441", issuer: "SAC", issued: "2025-02-01", expires: "2029-01-31", status: "verified" },
      { id: "d4", name: "Accredited scope annex", category: "laboratory", reference: "LA-0441/A3", issuer: "SAC", issued: "2026-02-14", expires: "2029-01-31", status: "verified" },
    ],
    riskFlags: [],
    audit: [
      { id: "a1", at: "2026-06-30 08:00", actor: "Wei Ling Tan", role: "partner", action: "Application submitted", detail: "4 documents attached" },
      { id: "a2", at: "2026-07-05 13:30", actor: "Amina Delacroix", role: "operator", action: "Approved", detail: "Listed as Quality & Control Partner, scope: Sn / Au" },
    ],
    decisionNote: "All accreditation evidence verified against BELAC/SAC registries. No adverse findings.",
  },
];

export const buyerSpecs: BuyerSpec[] = [
  {
    id: "spec-1",
    name: "VRG-CASS-2026 Cassiterite Grade A",
    buyerOrg: "Vos Refining Group",
    material: "Cassiterite concentrate",
    limits: [
      { analyte: "Sn", rule: "≥ 62 %", target: "62" },
      { analyte: "As", rule: "≤ 500 ppm", target: "500" },
      { analyte: "Pb", rule: "≤ 300 ppm", target: "300" },
      { analyte: "Moisture", rule: "≤ 3 %", target: "3" },
    ],
  },
  {
    id: "spec-2",
    name: "VRG-COL-2026 Coltan Standard",
    buyerOrg: "Vos Refining Group",
    material: "Coltan concentrate",
    limits: [
      { analyte: "Ta2O5", rule: "≥ 28 %", target: "28" },
      { analyte: "U + Th", rule: "≤ 1000 ppm", target: "1000" },
    ],
  },
];

export const samples: Sample[] = [
  {
    id: "s-1",
    ref: "SMP-2026-3391",
    material: "Cassiterite concentrate",
    lot: "KRM-LOT-1187",
    mineSite: "Kivu Ridge Pit 4",
    origin: "South Kivu, DRC",
    massKg: 12.5,
    registeredAt: "2026-08-05",
    minerOrg: "Kivu Ridge Minerals",
    partnerOrg: "Antwerp Assay Laboratories NV",
    buyerOrg: "Vos Refining Group",
    buyerSpecId: "spec-1",
    status: "reviewed",
    custody: [
      { id: "c1", at: "2026-08-05 07:10", actor: "Grace Tumaini", location: "Kivu Ridge Pit 4", action: "Sample drawn and sealed", sealIntact: true, hash: "0x9f1a…c4" },
      { id: "c2", at: "2026-08-06 15:40", actor: "Bukavu Logistics", location: "Bukavu depot", action: "Handover to transporter", sealIntact: true, hash: "0x22be…7d" },
      { id: "c3", at: "2026-08-09 09:05", actor: "Customs BE", location: "Antwerp port", action: "Border inspection", sealIntact: true, hash: "0x51cd…09" },
      { id: "c4", at: "2026-08-10 11:12", actor: "Karel Op de Beeck", location: "Antwerp Haven Lab", action: "Received at laboratory", sealIntact: true, hash: "0x7a30…e1" },
    ],
    testRequest: {
      id: "tr-1",
      requestedAt: "2026-08-10",
      priority: "standard",
      methods: ["ICP-MS (Sn, As, Pb)", "Moisture gravimetric"],
      turnaround: "5 working days",
      status: "complete",
    },
    results: [
      { id: "t1", analyte: "Sn", method: "ICP-MS", value: "64.8", unit: "%", spec: "≥ 62 %", verdict: "pass", uncertainty: "±0.4" },
      { id: "t2", analyte: "As", method: "ICP-MS", value: "412", unit: "ppm", spec: "≤ 500 ppm", verdict: "pass", uncertainty: "±18" },
      { id: "t3", analyte: "Pb", method: "ICP-MS", value: "318", unit: "ppm", spec: "≤ 300 ppm", verdict: "conditional", uncertainty: "±22" },
      { id: "t4", analyte: "Moisture", method: "Gravimetric", value: "2.1", unit: "%", spec: "≤ 3 %", verdict: "pass", uncertainty: "±0.1" },
    ],
    qualityReview: {
      reviewer: "Dr. Léon Mbaye",
      at: "2026-08-17",
      verdict: "conditional",
      note: "Pb marginally above limit but within combined measurement uncertainty; buyer concession required.",
    },
    audit: [
      { id: "a1", at: "2026-08-05 07:10", actor: "Grace Tumaini", role: "miner", action: "Sample registered", detail: "SMP-2026-3391 created for lot KRM-LOT-1187" },
      { id: "a2", at: "2026-08-10 11:12", actor: "Karel Op de Beeck", role: "partner", action: "Sample received", detail: "Seal verified intact" },
      { id: "a3", at: "2026-08-17 16:00", actor: "Dr. Léon Mbaye", role: "partner", action: "Quality review completed", detail: "Conditional verdict recorded" },
    ],
  },
  {
    id: "s-2",
    ref: "SMP-2026-3402",
    material: "Coltan concentrate",
    lot: "KRM-LOT-1191",
    mineSite: "Kivu Ridge Pit 2",
    origin: "South Kivu, DRC",
    massKg: 8,
    registeredAt: "2026-08-14",
    minerOrg: "Kivu Ridge Minerals",
    partnerOrg: "Antwerp Assay Laboratories NV",
    buyerOrg: "Vos Refining Group",
    buyerSpecId: "spec-2",
    status: "testing",
    custody: [
      { id: "c1", at: "2026-08-14 06:50", actor: "Grace Tumaini", location: "Kivu Ridge Pit 2", action: "Sample drawn and sealed", sealIntact: true, hash: "0x1188…aa" },
      { id: "c2", at: "2026-08-18 10:30", actor: "Karel Op de Beeck", location: "Antwerp Haven Lab", action: "Received at laboratory", sealIntact: true, hash: "0x4c02…3f" },
    ],
    testRequest: {
      id: "tr-2",
      requestedAt: "2026-08-18",
      priority: "expedited",
      methods: ["XRF (Ta2O5, Nb2O5)", "Gamma screen (U/Th)"],
      turnaround: "48 hours",
      status: "accepted",
    },
    results: [
      { id: "t1", analyte: "Ta2O5", method: "XRF", value: "—", unit: "%", spec: "≥ 28 %", verdict: "pending", uncertainty: "—" },
      { id: "t2", analyte: "U + Th", method: "Gamma screen", value: "—", unit: "ppm", spec: "≤ 1000 ppm", verdict: "pending", uncertainty: "—" },
    ],
    qualityReview: null,
    audit: [
      { id: "a1", at: "2026-08-14 06:50", actor: "Grace Tumaini", role: "miner", action: "Sample registered", detail: "SMP-2026-3402 created" },
      { id: "a2", at: "2026-08-18 10:30", actor: "Karel Op de Beeck", role: "partner", action: "Sample received", detail: "Expedited request accepted" },
    ],
  },
  {
    id: "s-3",
    ref: "SMP-2026-3377",
    material: "Cassiterite concentrate",
    lot: "KRM-LOT-1180",
    mineSite: "Kivu Ridge Pit 4",
    origin: "South Kivu, DRC",
    massKg: 11,
    registeredAt: "2026-07-22",
    minerOrg: "Kivu Ridge Minerals",
    partnerOrg: "Antwerp Assay Laboratories NV",
    buyerOrg: "Vos Refining Group",
    buyerSpecId: "spec-1",
    status: "certified",
    custody: [
      { id: "c1", at: "2026-07-22 06:30", actor: "Grace Tumaini", location: "Kivu Ridge Pit 4", action: "Sample drawn and sealed", sealIntact: true, hash: "0xab19…70" },
      { id: "c2", at: "2026-07-27 09:00", actor: "Karel Op de Beeck", location: "Antwerp Haven Lab", action: "Received at laboratory", sealIntact: true, hash: "0xcc41…12" },
    ],
    testRequest: {
      id: "tr-3",
      requestedAt: "2026-07-27",
      priority: "standard",
      methods: ["ICP-MS (Sn, As, Pb)"],
      turnaround: "5 working days",
      status: "complete",
    },
    results: [
      { id: "t1", analyte: "Sn", method: "ICP-MS", value: "66.2", unit: "%", spec: "≥ 62 %", verdict: "pass", uncertainty: "±0.4" },
      { id: "t2", analyte: "As", method: "ICP-MS", value: "205", unit: "ppm", spec: "≤ 500 ppm", verdict: "pass", uncertainty: "±12" },
      { id: "t3", analyte: "Pb", method: "ICP-MS", value: "140", unit: "ppm", spec: "≤ 300 ppm", verdict: "pass", uncertainty: "±10" },
    ],
    qualityReview: {
      reviewer: "Dr. Léon Mbaye",
      at: "2026-08-01",
      verdict: "pass",
      note: "All analytes within specification. Certificate issued.",
    },
    audit: [
      { id: "a1", at: "2026-07-22 06:30", actor: "Grace Tumaini", role: "miner", action: "Sample registered", detail: "SMP-2026-3377 created" },
      { id: "a2", at: "2026-08-01 12:00", actor: "Dr. Léon Mbaye", role: "partner", action: "Certificate issued", detail: "CERT-2026-0771" },
    ],
  },
  {
    id: "s-4",
    ref: "SMP-2026-3410",
    material: "Cassiterite concentrate",
    lot: "KRM-LOT-1194",
    mineSite: "Kivu Ridge Pit 1",
    origin: "South Kivu, DRC",
    massKg: 9.4,
    registeredAt: "2026-08-20",
    minerOrg: "Kivu Ridge Minerals",
    partnerOrg: "Antwerp Assay Laboratories NV",
    buyerOrg: "Vos Refining Group",
    buyerSpecId: "spec-1",
    status: "in_transit",
    custody: [
      { id: "c1", at: "2026-08-20 07:00", actor: "Grace Tumaini", location: "Kivu Ridge Pit 1", action: "Sample drawn and sealed", sealIntact: true, hash: "0xf301…b8" },
    ],
    testRequest: null,
    results: [],
    qualityReview: null,
    audit: [
      { id: "a1", at: "2026-08-20 07:00", actor: "Grace Tumaini", role: "miner", action: "Sample registered", detail: "SMP-2026-3410 created" },
    ],
  },
];

export const certificates: Certificate[] = [
  {
    id: "cert-1",
    ref: "CERT-2026-0771",
    sampleRef: "SMP-2026-3377",
    material: "Cassiterite concentrate",
    issuedAt: "2026-08-01",
    issuedBy: "Antwerp Assay Laboratories NV",
    validUntil: "2027-08-01",
    status: "active",
    verificationHash: "0x77c1e4a9be2f0d5138aa47c0",
    scans: 14,
  },
  {
    id: "cert-2",
    ref: "CERT-2026-0742",
    sampleRef: "SMP-2026-3301",
    material: "Gold doré",
    issuedAt: "2026-06-18",
    issuedBy: "Pacific Metals Assay Pte Ltd",
    validUntil: "2027-06-18",
    status: "revoked",
    verificationHash: "0x1acc90ff31b7772d0e5591aa",
    scans: 61,
  },
];

export const nonConformities: NonConformity[] = [
  {
    id: "ncr-1",
    ref: "NCR-2026-018",
    title: "Expired 3TG export handling permit",
    raisedAt: "2026-08-14",
    raisedBy: "Amina Delacroix",
    against: "Antwerp Assay Laboratories NV",
    severity: "major",
    status: "capa_submitted",
    detail: "Conditional permit EXP-3TG-8871 lapsed while 3TG scope remained active on the partner listing.",
    capa: [
      { id: "ca1", action: "Submit renewal receipt from Flemish Government", owner: "Dr. Léon Mbaye", due: "2026-08-29", status: "in_progress" },
      { id: "ca2", action: "Suspend 3TG intake until permit restored", owner: "Karel Op de Beeck", due: "2026-08-22", status: "complete" },
    ],
  },
  {
    id: "ncr-2",
    ref: "NCR-2026-014",
    title: "Proficiency test z-score deviation",
    raisedAt: "2026-08-02",
    raisedBy: "Amina Delacroix",
    against: "Nordic Ore Verification AB",
    severity: "minor",
    status: "open",
    detail: "z = 2.4 recorded on phosphorus in iron ore. Root cause analysis outstanding.",
    capa: [],
  },
];

export const today = now;
