/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActionsRouteImport } from './routes/app.actions'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppEnvironmentalRouteImport } from './routes/app.environmental'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppNonconformitiesRouteImport } from './routes/app.nonconformities'
import { Route as AppOrganisationsRouteImport } from './routes/app.organisations'
import { Route as AppProductionRouteImport } from './routes/app.production'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppSamplingRouteImport } from './routes/app.sampling'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingAccountRouteImport } from './routes/onboarding.account'
import { Route as OnboardingAdminRouteImport } from './routes/onboarding.admin'
import { Route as OnboardingApplicationRouteImport } from './routes/onboarding.application'
import { Route as OnboardingDashboardRouteImport } from './routes/onboarding.dashboard'
import { Route as OnboardingJoinRouteImport } from './routes/onboarding.join'
import { Route as OnboardingPathRouteImport } from './routes/onboarding.path'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as OnboardingSubmittedRouteImport } from './routes/onboarding.submitted'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding.verify'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as AppSitesIndexRouteImport } from './routes/app.sites.index'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentalRoute = AppEnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppNonconformitiesRoute = AppNonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsRoute = AppOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSamplingRoute = AppSamplingRouteImport.update({
  id: '/sampling',
  path: '/sampling',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAccountRoute = OnboardingAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAdminRoute = OnboardingAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingApplicationRoute = OnboardingApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDashboardRoute = OnboardingDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingJoinRoute = OnboardingJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPathRoute = OnboardingPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSubmittedRoute = OnboardingSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppSitesIndexRoute = AppSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/app/actions': typeof AppActionsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/organisations': typeof AppOrganisationsRoute
  '/app/production': typeof AppProductionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/sampling': typeof AppSamplingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/admin': typeof OnboardingAdminRoute
  '/onboarding/application': typeof OnboardingApplicationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/path': typeof OnboardingPathRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/submitted': typeof OnboardingSubmittedRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/sites/': typeof AppSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/app/actions': typeof AppActionsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/organisations': typeof AppOrganisationsRoute
  '/app/production': typeof AppProductionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/sampling': typeof AppSamplingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/admin': typeof OnboardingAdminRoute
  '/onboarding/application': typeof OnboardingApplicationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/path': typeof OnboardingPathRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/submitted': typeof OnboardingSubmittedRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/sites': typeof AppSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/app/actions': typeof AppActionsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/organisations': typeof AppOrganisationsRoute
  '/app/production': typeof AppProductionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/sampling': typeof AppSamplingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/admin': typeof OnboardingAdminRoute
  '/onboarding/application': typeof OnboardingApplicationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/path': typeof OnboardingPathRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/submitted': typeof OnboardingSubmittedRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/sites/': typeof AppSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/signin'
    | '/app/actions'
    | '/app/applications'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/environmental'
    | '/app/inspections'
    | '/app/inventory'
    | '/app/nonconformities'
    | '/app/organisations'
    | '/app/production'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/sampling'
    | '/app/transactions'
    | '/onboarding/account'
    | '/onboarding/admin'
    | '/onboarding/application'
    | '/onboarding/dashboard'
    | '/onboarding/join'
    | '/onboarding/path'
    | '/onboarding/role'
    | '/onboarding/submitted'
    | '/onboarding/verify'
    | '/onboarding/welcome'
    | '/app/'
    | '/onboarding/'
    | '/app/sites/$siteId'
    | '/app/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/app/actions'
    | '/app/applications'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/environmental'
    | '/app/inspections'
    | '/app/inventory'
    | '/app/nonconformities'
    | '/app/organisations'
    | '/app/production'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/sampling'
    | '/app/transactions'
    | '/onboarding/account'
    | '/onboarding/admin'
    | '/onboarding/application'
    | '/onboarding/dashboard'
    | '/onboarding/join'
    | '/onboarding/path'
    | '/onboarding/role'
    | '/onboarding/submitted'
    | '/onboarding/verify'
    | '/onboarding/welcome'
    | '/app'
    | '/onboarding'
    | '/app/sites/$siteId'
    | '/app/sites'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/signin'
    | '/app/actions'
    | '/app/applications'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/environmental'
    | '/app/inspections'
    | '/app/inventory'
    | '/app/nonconformities'
    | '/app/organisations'
    | '/app/production'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/sampling'
    | '/app/transactions'
    | '/onboarding/account'
    | '/onboarding/admin'
    | '/onboarding/application'
    | '/onboarding/dashboard'
    | '/onboarding/join'
    | '/onboarding/path'
    | '/onboarding/role'
    | '/onboarding/submitted'
    | '/onboarding/verify'
    | '/onboarding/welcome'
    | '/app/'
    | '/onboarding/'
    | '/app/sites/$siteId'
    | '/app/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/environmental': {
      id: '/app/environmental'
      path: '/environmental'
      fullPath: '/app/environmental'
      preLoaderRoute: typeof AppEnvironmentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nonconformities': {
      id: '/app/nonconformities'
      path: '/nonconformities'
      fullPath: '/app/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organisations': {
      id: '/app/organisations'
      path: '/organisations'
      fullPath: '/app/organisations'
      preLoaderRoute: typeof AppOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/production': {
      id: '/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sampling': {
      id: '/app/sampling'
      path: '/sampling'
      fullPath: '/app/sampling'
      preLoaderRoute: typeof AppSamplingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/account': {
      id: '/onboarding/account'
      path: '/account'
      fullPath: '/onboarding/account'
      preLoaderRoute: typeof OnboardingAccountRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/admin': {
      id: '/onboarding/admin'
      path: '/admin'
      fullPath: '/onboarding/admin'
      preLoaderRoute: typeof OnboardingAdminRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/application': {
      id: '/onboarding/application'
      path: '/application'
      fullPath: '/onboarding/application'
      preLoaderRoute: typeof OnboardingApplicationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/dashboard': {
      id: '/onboarding/dashboard'
      path: '/dashboard'
      fullPath: '/onboarding/dashboard'
      preLoaderRoute: typeof OnboardingDashboardRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/join': {
      id: '/onboarding/join'
      path: '/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof OnboardingJoinRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/path': {
      id: '/onboarding/path'
      path: '/path'
      fullPath: '/onboarding/path'
      preLoaderRoute: typeof OnboardingPathRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/submitted': {
      id: '/onboarding/submitted'
      path: '/submitted'
      fullPath: '/onboarding/submitted'
      preLoaderRoute: typeof OnboardingSubmittedRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/sites/': {
      id: '/app/sites/'
      path: '/sites'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AppSitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEnvironmentalRoute: typeof AppEnvironmentalRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppOrganisationsRoute: typeof AppOrganisationsRoute
  AppProductionRoute: typeof AppProductionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSamplingRoute: typeof AppSamplingRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRoute
  AppSitesIndexRoute: typeof AppSitesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppAuditRoute: AppAuditRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEnvironmentalRoute: AppEnvironmentalRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppOrganisationsRoute: AppOrganisationsRoute,
  AppProductionRoute: AppProductionRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppRiskRoute: AppRiskRoute,
  AppSamplingRoute: AppSamplingRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSitesSiteIdRoute: AppSitesSiteIdRoute,
  AppSitesIndexRoute: AppSitesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAccountRoute: typeof OnboardingAccountRoute
  OnboardingAdminRoute: typeof OnboardingAdminRoute
  OnboardingApplicationRoute: typeof OnboardingApplicationRoute
  OnboardingDashboardRoute: typeof OnboardingDashboardRoute
  OnboardingJoinRoute: typeof OnboardingJoinRoute
  OnboardingPathRoute: typeof OnboardingPathRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingSubmittedRoute: typeof OnboardingSubmittedRoute
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAccountRoute: OnboardingAccountRoute,
  OnboardingAdminRoute: OnboardingAdminRoute,
  OnboardingApplicationRoute: OnboardingApplicationRoute,
  OnboardingDashboardRoute: OnboardingDashboardRoute,
  OnboardingJoinRoute: OnboardingJoinRoute,
  OnboardingPathRoute: OnboardingPathRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingSubmittedRoute: OnboardingSubmittedRoute,
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
