/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ComplianceIndexRouteImport } from './routes/compliance.index'
import { Route as ComplianceIdRouteImport } from './routes/compliance.$id'
import { Route as RfqsIndexRouteImport } from './routes/rfqs.index'
import { Route as RfqsIdRouteImport } from './routes/rfqs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIdRoute = ComplianceIdRouteImport.update({
  id: '/compliance/$id',
  path: '/compliance/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsIndexRoute = RfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsIdRoute = RfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/compliance/$id': typeof ComplianceIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/rfqs/': typeof RfqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/compliance/$id': typeof ComplianceIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
  '/compliance': typeof ComplianceIndexRoute
  '/rfqs': typeof RfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/compliance/$id': typeof ComplianceIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/rfqs/': typeof RfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/marketplace'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/compliance/$id'
    | '/rfqs/$id'
    | '/compliance/'
    | '/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/marketplace'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/compliance/$id'
    | '/rfqs/$id'
    | '/compliance'
    | '/rfqs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/marketplace'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/compliance/$id'
    | '/rfqs/$id'
    | '/compliance/'
    | '/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceRoute: typeof FinanceRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  ComplianceIdRoute: typeof ComplianceIdRoute
  RfqsIdRoute: typeof RfqsIdRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
  RfqsIndexRoute: typeof RfqsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/$id': {
      id: '/compliance/$id'
      path: '/compliance/$id'
      fullPath: '/compliance/$id'
      preLoaderRoute: typeof ComplianceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs/': {
      id: '/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof RfqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs/$id': {
      id: '/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/rfqs/$id'
      preLoaderRoute: typeof RfqsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceRoute: FinanceRoute,
  MarketplaceRoute: MarketplaceRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  ComplianceIdRoute: ComplianceIdRoute,
  RfqsIdRoute: RfqsIdRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
  RfqsIndexRoute: RfqsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
