/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActionsRouteImport } from './routes/app.actions'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppEnvironmentalRouteImport } from './routes/app.environmental'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppNonconformitiesRouteImport } from './routes/app.nonconformities'
import { Route as AppOrganisationsRouteImport } from './routes/app.organisations'
import { Route as AppProductionRouteImport } from './routes/app.production'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppSamplingRouteImport } from './routes/app.sampling'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSitesIndexRouteImport } from './routes/app.sites.index'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentalRoute = AppEnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppNonconformitiesRoute = AppNonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsRoute = AppOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSamplingRoute = AppSamplingRouteImport.update({
  id: '/sampling',
  path: '/sampling',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesIndexRoute = AppSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/organisations': typeof AppOrganisationsRoute
  '/app/production': typeof AppProductionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/sampling': typeof AppSamplingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/sites/': typeof AppSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/actions': typeof AppActionsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/organisations': typeof AppOrganisationsRoute
  '/app/production': typeof AppProductionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/sampling': typeof AppSamplingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/sites': typeof AppSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/organisations': typeof AppOrganisationsRoute
  '/app/production': typeof AppProductionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/sampling': typeof AppSamplingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/sites/': typeof AppSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/applications'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/environmental'
    | '/app/inspections'
    | '/app/inventory'
    | '/app/nonconformities'
    | '/app/organisations'
    | '/app/production'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/sampling'
    | '/app/transactions'
    | '/app/'
    | '/app/sites/$siteId'
    | '/app/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/actions'
    | '/app/applications'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/environmental'
    | '/app/inspections'
    | '/app/inventory'
    | '/app/nonconformities'
    | '/app/organisations'
    | '/app/production'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/sampling'
    | '/app/transactions'
    | '/app'
    | '/app/sites/$siteId'
    | '/app/sites'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/applications'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/environmental'
    | '/app/inspections'
    | '/app/inventory'
    | '/app/nonconformities'
    | '/app/organisations'
    | '/app/production'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/sampling'
    | '/app/transactions'
    | '/app/'
    | '/app/sites/$siteId'
    | '/app/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/environmental': {
      id: '/app/environmental'
      path: '/environmental'
      fullPath: '/app/environmental'
      preLoaderRoute: typeof AppEnvironmentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nonconformities': {
      id: '/app/nonconformities'
      path: '/nonconformities'
      fullPath: '/app/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organisations': {
      id: '/app/organisations'
      path: '/organisations'
      fullPath: '/app/organisations'
      preLoaderRoute: typeof AppOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/production': {
      id: '/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sampling': {
      id: '/app/sampling'
      path: '/sampling'
      fullPath: '/app/sampling'
      preLoaderRoute: typeof AppSamplingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/': {
      id: '/app/sites/'
      path: '/sites'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AppSitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEnvironmentalRoute: typeof AppEnvironmentalRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppOrganisationsRoute: typeof AppOrganisationsRoute
  AppProductionRoute: typeof AppProductionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSamplingRoute: typeof AppSamplingRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRoute
  AppSitesIndexRoute: typeof AppSitesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppAuditRoute: AppAuditRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEnvironmentalRoute: AppEnvironmentalRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppOrganisationsRoute: AppOrganisationsRoute,
  AppProductionRoute: AppProductionRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppRiskRoute: AppRiskRoute,
  AppSamplingRoute: AppSamplingRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSitesSiteIdRoute: AppSitesSiteIdRoute,
  AppSitesIndexRoute: AppSitesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
