/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as OversightRouteImport } from './routes/oversight'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ExportersIndexRouteImport } from './routes/exporters.index'
import { Route as ExportersIdRouteImport } from './routes/exporters.$id'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments.index'
import { Route as ShipmentsIdRouteImport } from './routes/shipments.$id'
import { Route as ShipmentsNewRouteImport } from './routes/shipments.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const OversightRoute = OversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportersIndexRoute = ExportersIndexRouteImport.update({
  id: '/exporters/',
  path: '/exporters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportersIdRoute = ExportersIdRouteImport.update({
  id: '/exporters/$id',
  path: '/exporters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIdRoute = ShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsNewRoute = ShipmentsNewRouteImport.update({
  id: '/shipments/new',
  path: '/shipments/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/monitoring': typeof MonitoringRoute
  '/oversight': typeof OversightRoute
  '/queue': typeof QueueRoute
  '/exporters/$id': typeof ExportersIdRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/exporters/': typeof ExportersIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/monitoring': typeof MonitoringRoute
  '/oversight': typeof OversightRoute
  '/queue': typeof QueueRoute
  '/exporters/$id': typeof ExportersIdRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/exporters': typeof ExportersIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/monitoring': typeof MonitoringRoute
  '/oversight': typeof OversightRoute
  '/queue': typeof QueueRoute
  '/exporters/$id': typeof ExportersIdRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/exporters/': typeof ExportersIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/monitoring'
    | '/oversight'
    | '/queue'
    | '/exporters/$id'
    | '/shipments/$id'
    | '/shipments/new'
    | '/exporters/'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/monitoring'
    | '/oversight'
    | '/queue'
    | '/exporters/$id'
    | '/shipments/$id'
    | '/shipments/new'
    | '/exporters'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documents'
    | '/monitoring'
    | '/oversight'
    | '/queue'
    | '/exporters/$id'
    | '/shipments/$id'
    | '/shipments/new'
    | '/exporters/'
    | '/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  MonitoringRoute: typeof MonitoringRoute
  OversightRoute: typeof OversightRoute
  QueueRoute: typeof QueueRoute
  ExportersIdRoute: typeof ExportersIdRoute
  ShipmentsIdRoute: typeof ShipmentsIdRoute
  ShipmentsNewRoute: typeof ShipmentsNewRoute
  ExportersIndexRoute: typeof ExportersIndexRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversight': {
      id: '/oversight'
      path: '/oversight'
      fullPath: '/oversight'
      preLoaderRoute: typeof OversightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exporters/': {
      id: '/exporters/'
      path: '/exporters'
      fullPath: '/exporters/'
      preLoaderRoute: typeof ExportersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exporters/$id': {
      id: '/exporters/$id'
      path: '/exporters/$id'
      fullPath: '/exporters/$id'
      preLoaderRoute: typeof ExportersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/$id': {
      id: '/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof ShipmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/new': {
      id: '/shipments/new'
      path: '/shipments/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof ShipmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  MonitoringRoute: MonitoringRoute,
  OversightRoute: OversightRoute,
  QueueRoute: QueueRoute,
  ExportersIdRoute: ExportersIdRoute,
  ShipmentsIdRoute: ShipmentsIdRoute,
  ShipmentsNewRoute: ShipmentsNewRoute,
  ExportersIndexRoute: ExportersIndexRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
