/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalApplicationRecordRouteImport } from './routes/portal.application-record'
import { Route as PortalCommitmentsRouteImport } from './routes/portal.commitments'
import { Route as PortalComplianceRouteImport } from './routes/portal.compliance'
import { Route as PortalCorrectiveActionsRouteImport } from './routes/portal.corrective-actions'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalEquipmentRouteImport } from './routes/portal.equipment'
import { Route as PortalExportsRouteImport } from './routes/portal.exports'
import { Route as PortalFinanceRouteImport } from './routes/portal.finance'
import { Route as PortalInventoryRouteImport } from './routes/portal.inventory'
import { Route as PortalLogisticsRouteImport } from './routes/portal.logistics'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalOrganisationRouteImport } from './routes/portal.organisation'
import { Route as PortalProcessingRouteImport } from './routes/portal.processing'
import { Route as PortalProductionRouteImport } from './routes/portal.production'
import { Route as PortalQualityRouteImport } from './routes/portal.quality'
import { Route as PortalReportsRouteImport } from './routes/portal.reports'
import { Route as PortalRequestsRouteImport } from './routes/portal.requests'
import { Route as PortalRfqsRouteImport } from './routes/portal.rfqs'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalSitesRouteImport } from './routes/portal.sites'
import { Route as PortalTransactionsRouteImport } from './routes/portal.transactions'
import { Route as PortalWarehousingRouteImport } from './routes/portal.warehousing'
import { Route as PortalSitesIndexRouteImport } from './routes/portal.sites.index'
import { Route as PortalSitesSiteIdRouteImport } from './routes/portal.sites.$siteId'
import { Route as PortalTransactionsIndexRouteImport } from './routes/portal.transactions.index'
import { Route as PortalTransactionsTransactionIdRouteImport } from './routes/portal.transactions.$transactionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationRecordRoute = PortalApplicationRecordRouteImport.update({
  id: '/application-record',
  path: '/application-record',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCommitmentsRoute = PortalCommitmentsRouteImport.update({
  id: '/commitments',
  path: '/commitments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalComplianceRoute = PortalComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCorrectiveActionsRoute = PortalCorrectiveActionsRouteImport.update({
  id: '/corrective-actions',
  path: '/corrective-actions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEquipmentRoute = PortalEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExportsRoute = PortalExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceRoute = PortalFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInventoryRoute = PortalInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLogisticsRoute = PortalLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrganisationRoute = PortalOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProcessingRoute = PortalProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductionRoute = PortalProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQualityRoute = PortalQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRequestsRoute = PortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRfqsRoute = PortalRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSitesRoute = PortalSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTransactionsRoute = PortalTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWarehousingRoute = PortalWarehousingRouteImport.update({
  id: '/warehousing',
  path: '/warehousing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSitesIndexRoute = PortalSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalSitesRoute,
} as any)
const PortalSitesSiteIdRoute = PortalSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => PortalSitesRoute,
} as any)
const PortalTransactionsIndexRoute = PortalTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTransactionsRoute,
} as any)
const PortalTransactionsTransactionIdRoute =
  PortalTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => PortalTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/submitted': typeof SubmittedRoute
  '/verify': typeof VerifyRoute
  '/portal/application-record': typeof PortalApplicationRecordRoute
  '/portal/commitments': typeof PortalCommitmentsRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/corrective-actions': typeof PortalCorrectiveActionsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/equipment': typeof PortalEquipmentRoute
  '/portal/exports': typeof PortalExportsRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/inventory': typeof PortalInventoryRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/organisation': typeof PortalOrganisationRoute
  '/portal/processing': typeof PortalProcessingRoute
  '/portal/production': typeof PortalProductionRoute
  '/portal/quality': typeof PortalQualityRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/rfqs': typeof PortalRfqsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/sites': typeof PortalSitesRouteWithChildren
  '/portal/transactions': typeof PortalTransactionsRouteWithChildren
  '/portal/warehousing': typeof PortalWarehousingRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/sites/$siteId': typeof PortalSitesSiteIdRoute
  '/portal/transactions/$transactionId': typeof PortalTransactionsTransactionIdRoute
  '/portal/sites/': typeof PortalSitesIndexRoute
  '/portal/transactions/': typeof PortalTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/submitted': typeof SubmittedRoute
  '/verify': typeof VerifyRoute
  '/portal/application-record': typeof PortalApplicationRecordRoute
  '/portal/commitments': typeof PortalCommitmentsRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/corrective-actions': typeof PortalCorrectiveActionsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/equipment': typeof PortalEquipmentRoute
  '/portal/exports': typeof PortalExportsRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/inventory': typeof PortalInventoryRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/organisation': typeof PortalOrganisationRoute
  '/portal/processing': typeof PortalProcessingRoute
  '/portal/production': typeof PortalProductionRoute
  '/portal/quality': typeof PortalQualityRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/rfqs': typeof PortalRfqsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/warehousing': typeof PortalWarehousingRoute
  '/portal': typeof PortalIndexRoute
  '/portal/sites/$siteId': typeof PortalSitesSiteIdRoute
  '/portal/transactions/$transactionId': typeof PortalTransactionsTransactionIdRoute
  '/portal/sites': typeof PortalSitesIndexRoute
  '/portal/transactions': typeof PortalTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/submitted': typeof SubmittedRoute
  '/verify': typeof VerifyRoute
  '/portal/application-record': typeof PortalApplicationRecordRoute
  '/portal/commitments': typeof PortalCommitmentsRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/corrective-actions': typeof PortalCorrectiveActionsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/equipment': typeof PortalEquipmentRoute
  '/portal/exports': typeof PortalExportsRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/inventory': typeof PortalInventoryRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/organisation': typeof PortalOrganisationRoute
  '/portal/processing': typeof PortalProcessingRoute
  '/portal/production': typeof PortalProductionRoute
  '/portal/quality': typeof PortalQualityRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/rfqs': typeof PortalRfqsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/sites': typeof PortalSitesRouteWithChildren
  '/portal/transactions': typeof PortalTransactionsRouteWithChildren
  '/portal/warehousing': typeof PortalWarehousingRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/sites/$siteId': typeof PortalSitesSiteIdRoute
  '/portal/transactions/$transactionId': typeof PortalTransactionsTransactionIdRoute
  '/portal/sites/': typeof PortalSitesIndexRoute
  '/portal/transactions/': typeof PortalTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application'
    | '/auth'
    | '/portal'
    | '/signup'
    | '/submitted'
    | '/verify'
    | '/portal/application-record'
    | '/portal/commitments'
    | '/portal/compliance'
    | '/portal/corrective-actions'
    | '/portal/documents'
    | '/portal/equipment'
    | '/portal/exports'
    | '/portal/finance'
    | '/portal/inventory'
    | '/portal/logistics'
    | '/portal/notifications'
    | '/portal/organisation'
    | '/portal/processing'
    | '/portal/production'
    | '/portal/quality'
    | '/portal/reports'
    | '/portal/requests'
    | '/portal/rfqs'
    | '/portal/settings'
    | '/portal/sites'
    | '/portal/transactions'
    | '/portal/warehousing'
    | '/portal/'
    | '/portal/sites/$siteId'
    | '/portal/transactions/$transactionId'
    | '/portal/sites/'
    | '/portal/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application'
    | '/auth'
    | '/signup'
    | '/submitted'
    | '/verify'
    | '/portal/application-record'
    | '/portal/commitments'
    | '/portal/compliance'
    | '/portal/corrective-actions'
    | '/portal/documents'
    | '/portal/equipment'
    | '/portal/exports'
    | '/portal/finance'
    | '/portal/inventory'
    | '/portal/logistics'
    | '/portal/notifications'
    | '/portal/organisation'
    | '/portal/processing'
    | '/portal/production'
    | '/portal/quality'
    | '/portal/reports'
    | '/portal/requests'
    | '/portal/rfqs'
    | '/portal/settings'
    | '/portal/warehousing'
    | '/portal'
    | '/portal/sites/$siteId'
    | '/portal/transactions/$transactionId'
    | '/portal/sites'
    | '/portal/transactions'
  id:
    | '__root__'
    | '/'
    | '/application'
    | '/auth'
    | '/portal'
    | '/signup'
    | '/submitted'
    | '/verify'
    | '/portal/application-record'
    | '/portal/commitments'
    | '/portal/compliance'
    | '/portal/corrective-actions'
    | '/portal/documents'
    | '/portal/equipment'
    | '/portal/exports'
    | '/portal/finance'
    | '/portal/inventory'
    | '/portal/logistics'
    | '/portal/notifications'
    | '/portal/organisation'
    | '/portal/processing'
    | '/portal/production'
    | '/portal/quality'
    | '/portal/reports'
    | '/portal/requests'
    | '/portal/rfqs'
    | '/portal/settings'
    | '/portal/sites'
    | '/portal/transactions'
    | '/portal/warehousing'
    | '/portal/'
    | '/portal/sites/$siteId'
    | '/portal/transactions/$transactionId'
    | '/portal/sites/'
    | '/portal/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationRoute: typeof ApplicationRoute
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
  SubmittedRoute: typeof SubmittedRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/application-record': {
      id: '/portal/application-record'
      path: '/application-record'
      fullPath: '/portal/application-record'
      preLoaderRoute: typeof PortalApplicationRecordRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/commitments': {
      id: '/portal/commitments'
      path: '/commitments'
      fullPath: '/portal/commitments'
      preLoaderRoute: typeof PortalCommitmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/compliance': {
      id: '/portal/compliance'
      path: '/compliance'
      fullPath: '/portal/compliance'
      preLoaderRoute: typeof PortalComplianceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/corrective-actions': {
      id: '/portal/corrective-actions'
      path: '/corrective-actions'
      fullPath: '/portal/corrective-actions'
      preLoaderRoute: typeof PortalCorrectiveActionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/equipment': {
      id: '/portal/equipment'
      path: '/equipment'
      fullPath: '/portal/equipment'
      preLoaderRoute: typeof PortalEquipmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/exports': {
      id: '/portal/exports'
      path: '/exports'
      fullPath: '/portal/exports'
      preLoaderRoute: typeof PortalExportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/finance': {
      id: '/portal/finance'
      path: '/finance'
      fullPath: '/portal/finance'
      preLoaderRoute: typeof PortalFinanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inventory': {
      id: '/portal/inventory'
      path: '/inventory'
      fullPath: '/portal/inventory'
      preLoaderRoute: typeof PortalInventoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/logistics': {
      id: '/portal/logistics'
      path: '/logistics'
      fullPath: '/portal/logistics'
      preLoaderRoute: typeof PortalLogisticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/organisation': {
      id: '/portal/organisation'
      path: '/organisation'
      fullPath: '/portal/organisation'
      preLoaderRoute: typeof PortalOrganisationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/processing': {
      id: '/portal/processing'
      path: '/processing'
      fullPath: '/portal/processing'
      preLoaderRoute: typeof PortalProcessingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/production': {
      id: '/portal/production'
      path: '/production'
      fullPath: '/portal/production'
      preLoaderRoute: typeof PortalProductionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quality': {
      id: '/portal/quality'
      path: '/quality'
      fullPath: '/portal/quality'
      preLoaderRoute: typeof PortalQualityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/requests': {
      id: '/portal/requests'
      path: '/requests'
      fullPath: '/portal/requests'
      preLoaderRoute: typeof PortalRequestsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/rfqs': {
      id: '/portal/rfqs'
      path: '/rfqs'
      fullPath: '/portal/rfqs'
      preLoaderRoute: typeof PortalRfqsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/sites': {
      id: '/portal/sites'
      path: '/sites'
      fullPath: '/portal/sites'
      preLoaderRoute: typeof PortalSitesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/transactions': {
      id: '/portal/transactions'
      path: '/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof PortalTransactionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/warehousing': {
      id: '/portal/warehousing'
      path: '/warehousing'
      fullPath: '/portal/warehousing'
      preLoaderRoute: typeof PortalWarehousingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/sites/': {
      id: '/portal/sites/'
      path: '/'
      fullPath: '/portal/sites/'
      preLoaderRoute: typeof PortalSitesIndexRouteImport
      parentRoute: typeof PortalSitesRoute
    }
    '/portal/sites/$siteId': {
      id: '/portal/sites/$siteId'
      path: '/$siteId'
      fullPath: '/portal/sites/$siteId'
      preLoaderRoute: typeof PortalSitesSiteIdRouteImport
      parentRoute: typeof PortalSitesRoute
    }
    '/portal/transactions/': {
      id: '/portal/transactions/'
      path: '/'
      fullPath: '/portal/transactions/'
      preLoaderRoute: typeof PortalTransactionsIndexRouteImport
      parentRoute: typeof PortalTransactionsRoute
    }
    '/portal/transactions/$transactionId': {
      id: '/portal/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/portal/transactions/$transactionId'
      preLoaderRoute: typeof PortalTransactionsTransactionIdRouteImport
      parentRoute: typeof PortalTransactionsRoute
    }
  }
}

interface PortalSitesRouteChildren {
  PortalSitesSiteIdRoute: typeof PortalSitesSiteIdRoute
  PortalSitesIndexRoute: typeof PortalSitesIndexRoute
}

const PortalSitesRouteChildren: PortalSitesRouteChildren = {
  PortalSitesSiteIdRoute: PortalSitesSiteIdRoute,
  PortalSitesIndexRoute: PortalSitesIndexRoute,
}

const PortalSitesRouteWithChildren = PortalSitesRoute._addFileChildren(
  PortalSitesRouteChildren,
)

interface PortalTransactionsRouteChildren {
  PortalTransactionsTransactionIdRoute: typeof PortalTransactionsTransactionIdRoute
  PortalTransactionsIndexRoute: typeof PortalTransactionsIndexRoute
}

const PortalTransactionsRouteChildren: PortalTransactionsRouteChildren = {
  PortalTransactionsTransactionIdRoute: PortalTransactionsTransactionIdRoute,
  PortalTransactionsIndexRoute: PortalTransactionsIndexRoute,
}

const PortalTransactionsRouteWithChildren =
  PortalTransactionsRoute._addFileChildren(PortalTransactionsRouteChildren)

interface PortalRouteChildren {
  PortalApplicationRecordRoute: typeof PortalApplicationRecordRoute
  PortalCommitmentsRoute: typeof PortalCommitmentsRoute
  PortalComplianceRoute: typeof PortalComplianceRoute
  PortalCorrectiveActionsRoute: typeof PortalCorrectiveActionsRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalEquipmentRoute: typeof PortalEquipmentRoute
  PortalExportsRoute: typeof PortalExportsRoute
  PortalFinanceRoute: typeof PortalFinanceRoute
  PortalInventoryRoute: typeof PortalInventoryRoute
  PortalLogisticsRoute: typeof PortalLogisticsRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalOrganisationRoute: typeof PortalOrganisationRoute
  PortalProcessingRoute: typeof PortalProcessingRoute
  PortalProductionRoute: typeof PortalProductionRoute
  PortalQualityRoute: typeof PortalQualityRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalRequestsRoute: typeof PortalRequestsRoute
  PortalRfqsRoute: typeof PortalRfqsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalSitesRoute: typeof PortalSitesRouteWithChildren
  PortalTransactionsRoute: typeof PortalTransactionsRouteWithChildren
  PortalWarehousingRoute: typeof PortalWarehousingRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApplicationRecordRoute: PortalApplicationRecordRoute,
  PortalCommitmentsRoute: PortalCommitmentsRoute,
  PortalComplianceRoute: PortalComplianceRoute,
  PortalCorrectiveActionsRoute: PortalCorrectiveActionsRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalEquipmentRoute: PortalEquipmentRoute,
  PortalExportsRoute: PortalExportsRoute,
  PortalFinanceRoute: PortalFinanceRoute,
  PortalInventoryRoute: PortalInventoryRoute,
  PortalLogisticsRoute: PortalLogisticsRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalOrganisationRoute: PortalOrganisationRoute,
  PortalProcessingRoute: PortalProcessingRoute,
  PortalProductionRoute: PortalProductionRoute,
  PortalQualityRoute: PortalQualityRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalRequestsRoute: PortalRequestsRoute,
  PortalRfqsRoute: PortalRfqsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalSitesRoute: PortalSitesRouteWithChildren,
  PortalTransactionsRoute: PortalTransactionsRouteWithChildren,
  PortalWarehousingRoute: PortalWarehousingRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationRoute: ApplicationRoute,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
  SubmittedRoute: SubmittedRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
