/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as OperatorApplicationsRouteImport } from './routes/operator.applications'
import { Route as OperatorAuditRouteImport } from './routes/operator.audit'
import { Route as OperatorDocumentsRouteImport } from './routes/operator.documents'
import { Route as OperatorNotificationsRouteImport } from './routes/operator.notifications'
import { Route as OperatorProfileRouteImport } from './routes/operator.profile'
import { Route as OperatorReportsRouteImport } from './routes/operator.reports'
import { Route as OperatorRequestsRouteImport } from './routes/operator.requests'
import { Route as OperatorRiskRouteImport } from './routes/operator.risk'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerActivityRouteImport } from './routes/partner.activity'
import { Route as PartnerApplicationRouteImport } from './routes/partner.application'
import { Route as PartnerCompanyRouteImport } from './routes/partner.company'
import { Route as PartnerDocumentsRouteImport } from './routes/partner.documents'
import { Route as PartnerDriversRouteImport } from './routes/partner.drivers'
import { Route as PartnerFleetRouteImport } from './routes/partner.fleet'
import { Route as PartnerRequestsRouteImport } from './routes/partner.requests'
import { Route as RegulatorIndexRouteImport } from './routes/regulator.index'
import { Route as RegulatorAlertsRouteImport } from './routes/regulator.alerts'
import { Route as RegulatorComplianceRouteImport } from './routes/regulator.compliance'
import { Route as RegulatorExpiringRouteImport } from './routes/regulator.expiring'
import { Route as RegulatorNotificationsRouteImport } from './routes/regulator.notifications'
import { Route as RegulatorOperatorsRouteImport } from './routes/regulator.operators'
import { Route as RegulatorReportsRouteImport } from './routes/regulator.reports'
import { Route as OperatorApplicationsCompanyIdRouteImport } from './routes/operator.applications.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorApplicationsRoute = OperatorApplicationsRouteImport.update({
  id: '/operator/applications',
  path: '/operator/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorAuditRoute = OperatorAuditRouteImport.update({
  id: '/operator/audit',
  path: '/operator/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorDocumentsRoute = OperatorDocumentsRouteImport.update({
  id: '/operator/documents',
  path: '/operator/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorNotificationsRoute = OperatorNotificationsRouteImport.update({
  id: '/operator/notifications',
  path: '/operator/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorProfileRoute = OperatorProfileRouteImport.update({
  id: '/operator/profile',
  path: '/operator/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorReportsRoute = OperatorReportsRouteImport.update({
  id: '/operator/reports',
  path: '/operator/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRequestsRoute = OperatorRequestsRouteImport.update({
  id: '/operator/requests',
  path: '/operator/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRiskRoute = OperatorRiskRouteImport.update({
  id: '/operator/risk',
  path: '/operator/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerActivityRoute = PartnerActivityRouteImport.update({
  id: '/partner/activity',
  path: '/partner/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplicationRoute = PartnerApplicationRouteImport.update({
  id: '/partner/application',
  path: '/partner/application',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCompanyRoute = PartnerCompanyRouteImport.update({
  id: '/partner/company',
  path: '/partner/company',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDocumentsRoute = PartnerDocumentsRouteImport.update({
  id: '/partner/documents',
  path: '/partner/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDriversRoute = PartnerDriversRouteImport.update({
  id: '/partner/drivers',
  path: '/partner/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerFleetRoute = PartnerFleetRouteImport.update({
  id: '/partner/fleet',
  path: '/partner/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRequestsRoute = PartnerRequestsRouteImport.update({
  id: '/partner/requests',
  path: '/partner/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorIndexRoute = RegulatorIndexRouteImport.update({
  id: '/regulator/',
  path: '/regulator/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorAlertsRoute = RegulatorAlertsRouteImport.update({
  id: '/regulator/alerts',
  path: '/regulator/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorComplianceRoute = RegulatorComplianceRouteImport.update({
  id: '/regulator/compliance',
  path: '/regulator/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorExpiringRoute = RegulatorExpiringRouteImport.update({
  id: '/regulator/expiring',
  path: '/regulator/expiring',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorNotificationsRoute = RegulatorNotificationsRouteImport.update({
  id: '/regulator/notifications',
  path: '/regulator/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorOperatorsRoute = RegulatorOperatorsRouteImport.update({
  id: '/regulator/operators',
  path: '/regulator/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorReportsRoute = RegulatorReportsRouteImport.update({
  id: '/regulator/reports',
  path: '/regulator/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorApplicationsCompanyIdRoute =
  OperatorApplicationsCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => OperatorApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/operator/applications': typeof OperatorApplicationsRouteWithChildren
  '/operator/audit': typeof OperatorAuditRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/requests': typeof OperatorRequestsRoute
  '/operator/risk': typeof OperatorRiskRoute
  '/partner/activity': typeof PartnerActivityRoute
  '/partner/application': typeof PartnerApplicationRoute
  '/partner/company': typeof PartnerCompanyRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/drivers': typeof PartnerDriversRoute
  '/partner/fleet': typeof PartnerFleetRoute
  '/partner/requests': typeof PartnerRequestsRoute
  '/regulator/alerts': typeof RegulatorAlertsRoute
  '/regulator/compliance': typeof RegulatorComplianceRoute
  '/regulator/expiring': typeof RegulatorExpiringRoute
  '/regulator/notifications': typeof RegulatorNotificationsRoute
  '/regulator/operators': typeof RegulatorOperatorsRoute
  '/regulator/reports': typeof RegulatorReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/regulator/': typeof RegulatorIndexRoute
  '/operator/applications/$companyId': typeof OperatorApplicationsCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operator/applications': typeof OperatorApplicationsRouteWithChildren
  '/operator/audit': typeof OperatorAuditRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/requests': typeof OperatorRequestsRoute
  '/operator/risk': typeof OperatorRiskRoute
  '/partner/activity': typeof PartnerActivityRoute
  '/partner/application': typeof PartnerApplicationRoute
  '/partner/company': typeof PartnerCompanyRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/drivers': typeof PartnerDriversRoute
  '/partner/fleet': typeof PartnerFleetRoute
  '/partner/requests': typeof PartnerRequestsRoute
  '/regulator/alerts': typeof RegulatorAlertsRoute
  '/regulator/compliance': typeof RegulatorComplianceRoute
  '/regulator/expiring': typeof RegulatorExpiringRoute
  '/regulator/notifications': typeof RegulatorNotificationsRoute
  '/regulator/operators': typeof RegulatorOperatorsRoute
  '/regulator/reports': typeof RegulatorReportsRoute
  '/admin': typeof AdminIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/regulator': typeof RegulatorIndexRoute
  '/operator/applications/$companyId': typeof OperatorApplicationsCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/operator/applications': typeof OperatorApplicationsRouteWithChildren
  '/operator/audit': typeof OperatorAuditRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/requests': typeof OperatorRequestsRoute
  '/operator/risk': typeof OperatorRiskRoute
  '/partner/activity': typeof PartnerActivityRoute
  '/partner/application': typeof PartnerApplicationRoute
  '/partner/company': typeof PartnerCompanyRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/drivers': typeof PartnerDriversRoute
  '/partner/fleet': typeof PartnerFleetRoute
  '/partner/requests': typeof PartnerRequestsRoute
  '/regulator/alerts': typeof RegulatorAlertsRoute
  '/regulator/compliance': typeof RegulatorComplianceRoute
  '/regulator/expiring': typeof RegulatorExpiringRoute
  '/regulator/notifications': typeof RegulatorNotificationsRoute
  '/regulator/operators': typeof RegulatorOperatorsRoute
  '/regulator/reports': typeof RegulatorReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/regulator/': typeof RegulatorIndexRoute
  '/operator/applications/$companyId': typeof OperatorApplicationsCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/operator/applications'
    | '/operator/audit'
    | '/operator/documents'
    | '/operator/notifications'
    | '/operator/profile'
    | '/operator/reports'
    | '/operator/requests'
    | '/operator/risk'
    | '/partner/activity'
    | '/partner/application'
    | '/partner/company'
    | '/partner/documents'
    | '/partner/drivers'
    | '/partner/fleet'
    | '/partner/requests'
    | '/regulator/alerts'
    | '/regulator/compliance'
    | '/regulator/expiring'
    | '/regulator/notifications'
    | '/regulator/operators'
    | '/regulator/reports'
    | '/admin/'
    | '/operator/'
    | '/partner/'
    | '/regulator/'
    | '/operator/applications/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/operator/applications'
    | '/operator/audit'
    | '/operator/documents'
    | '/operator/notifications'
    | '/operator/profile'
    | '/operator/reports'
    | '/operator/requests'
    | '/operator/risk'
    | '/partner/activity'
    | '/partner/application'
    | '/partner/company'
    | '/partner/documents'
    | '/partner/drivers'
    | '/partner/fleet'
    | '/partner/requests'
    | '/regulator/alerts'
    | '/regulator/compliance'
    | '/regulator/expiring'
    | '/regulator/notifications'
    | '/regulator/operators'
    | '/regulator/reports'
    | '/admin'
    | '/operator'
    | '/partner'
    | '/regulator'
    | '/operator/applications/$companyId'
  id:
    | '__root__'
    | '/'
    | '/operator/applications'
    | '/operator/audit'
    | '/operator/documents'
    | '/operator/notifications'
    | '/operator/profile'
    | '/operator/reports'
    | '/operator/requests'
    | '/operator/risk'
    | '/partner/activity'
    | '/partner/application'
    | '/partner/company'
    | '/partner/documents'
    | '/partner/drivers'
    | '/partner/fleet'
    | '/partner/requests'
    | '/regulator/alerts'
    | '/regulator/compliance'
    | '/regulator/expiring'
    | '/regulator/notifications'
    | '/regulator/operators'
    | '/regulator/reports'
    | '/admin/'
    | '/operator/'
    | '/partner/'
    | '/regulator/'
    | '/operator/applications/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OperatorApplicationsRoute: typeof OperatorApplicationsRouteWithChildren
  OperatorAuditRoute: typeof OperatorAuditRoute
  OperatorDocumentsRoute: typeof OperatorDocumentsRoute
  OperatorNotificationsRoute: typeof OperatorNotificationsRoute
  OperatorProfileRoute: typeof OperatorProfileRoute
  OperatorReportsRoute: typeof OperatorReportsRoute
  OperatorRequestsRoute: typeof OperatorRequestsRoute
  OperatorRiskRoute: typeof OperatorRiskRoute
  PartnerActivityRoute: typeof PartnerActivityRoute
  PartnerApplicationRoute: typeof PartnerApplicationRoute
  PartnerCompanyRoute: typeof PartnerCompanyRoute
  PartnerDocumentsRoute: typeof PartnerDocumentsRoute
  PartnerDriversRoute: typeof PartnerDriversRoute
  PartnerFleetRoute: typeof PartnerFleetRoute
  PartnerRequestsRoute: typeof PartnerRequestsRoute
  RegulatorAlertsRoute: typeof RegulatorAlertsRoute
  RegulatorComplianceRoute: typeof RegulatorComplianceRoute
  RegulatorExpiringRoute: typeof RegulatorExpiringRoute
  RegulatorNotificationsRoute: typeof RegulatorNotificationsRoute
  RegulatorOperatorsRoute: typeof RegulatorOperatorsRoute
  RegulatorReportsRoute: typeof RegulatorReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  RegulatorIndexRoute: typeof RegulatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/applications': {
      id: '/operator/applications'
      path: '/operator/applications'
      fullPath: '/operator/applications'
      preLoaderRoute: typeof OperatorApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/audit': {
      id: '/operator/audit'
      path: '/operator/audit'
      fullPath: '/operator/audit'
      preLoaderRoute: typeof OperatorAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/documents': {
      id: '/operator/documents'
      path: '/operator/documents'
      fullPath: '/operator/documents'
      preLoaderRoute: typeof OperatorDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/notifications': {
      id: '/operator/notifications'
      path: '/operator/notifications'
      fullPath: '/operator/notifications'
      preLoaderRoute: typeof OperatorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/profile': {
      id: '/operator/profile'
      path: '/operator/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof OperatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/reports': {
      id: '/operator/reports'
      path: '/operator/reports'
      fullPath: '/operator/reports'
      preLoaderRoute: typeof OperatorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/requests': {
      id: '/operator/requests'
      path: '/operator/requests'
      fullPath: '/operator/requests'
      preLoaderRoute: typeof OperatorRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/risk': {
      id: '/operator/risk'
      path: '/operator/risk'
      fullPath: '/operator/risk'
      preLoaderRoute: typeof OperatorRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/activity': {
      id: '/partner/activity'
      path: '/partner/activity'
      fullPath: '/partner/activity'
      preLoaderRoute: typeof PartnerActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/application': {
      id: '/partner/application'
      path: '/partner/application'
      fullPath: '/partner/application'
      preLoaderRoute: typeof PartnerApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/company': {
      id: '/partner/company'
      path: '/partner/company'
      fullPath: '/partner/company'
      preLoaderRoute: typeof PartnerCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/documents': {
      id: '/partner/documents'
      path: '/partner/documents'
      fullPath: '/partner/documents'
      preLoaderRoute: typeof PartnerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/drivers': {
      id: '/partner/drivers'
      path: '/partner/drivers'
      fullPath: '/partner/drivers'
      preLoaderRoute: typeof PartnerDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/fleet': {
      id: '/partner/fleet'
      path: '/partner/fleet'
      fullPath: '/partner/fleet'
      preLoaderRoute: typeof PartnerFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/requests': {
      id: '/partner/requests'
      path: '/partner/requests'
      fullPath: '/partner/requests'
      preLoaderRoute: typeof PartnerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/': {
      id: '/regulator/'
      path: '/regulator'
      fullPath: '/regulator/'
      preLoaderRoute: typeof RegulatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/alerts': {
      id: '/regulator/alerts'
      path: '/regulator/alerts'
      fullPath: '/regulator/alerts'
      preLoaderRoute: typeof RegulatorAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/compliance': {
      id: '/regulator/compliance'
      path: '/regulator/compliance'
      fullPath: '/regulator/compliance'
      preLoaderRoute: typeof RegulatorComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/expiring': {
      id: '/regulator/expiring'
      path: '/regulator/expiring'
      fullPath: '/regulator/expiring'
      preLoaderRoute: typeof RegulatorExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/notifications': {
      id: '/regulator/notifications'
      path: '/regulator/notifications'
      fullPath: '/regulator/notifications'
      preLoaderRoute: typeof RegulatorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/operators': {
      id: '/regulator/operators'
      path: '/regulator/operators'
      fullPath: '/regulator/operators'
      preLoaderRoute: typeof RegulatorOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/reports': {
      id: '/regulator/reports'
      path: '/regulator/reports'
      fullPath: '/regulator/reports'
      preLoaderRoute: typeof RegulatorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/applications/$companyId': {
      id: '/operator/applications/$companyId'
      path: '/$companyId'
      fullPath: '/operator/applications/$companyId'
      preLoaderRoute: typeof OperatorApplicationsCompanyIdRouteImport
      parentRoute: typeof OperatorApplicationsRoute
    }
  }
}

interface OperatorApplicationsRouteChildren {
  OperatorApplicationsCompanyIdRoute: typeof OperatorApplicationsCompanyIdRoute
}

const OperatorApplicationsRouteChildren: OperatorApplicationsRouteChildren = {
  OperatorApplicationsCompanyIdRoute: OperatorApplicationsCompanyIdRoute,
}

const OperatorApplicationsRouteWithChildren =
  OperatorApplicationsRoute._addFileChildren(OperatorApplicationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OperatorApplicationsRoute: OperatorApplicationsRouteWithChildren,
  OperatorAuditRoute: OperatorAuditRoute,
  OperatorDocumentsRoute: OperatorDocumentsRoute,
  OperatorNotificationsRoute: OperatorNotificationsRoute,
  OperatorProfileRoute: OperatorProfileRoute,
  OperatorReportsRoute: OperatorReportsRoute,
  OperatorRequestsRoute: OperatorRequestsRoute,
  OperatorRiskRoute: OperatorRiskRoute,
  PartnerActivityRoute: PartnerActivityRoute,
  PartnerApplicationRoute: PartnerApplicationRoute,
  PartnerCompanyRoute: PartnerCompanyRoute,
  PartnerDocumentsRoute: PartnerDocumentsRoute,
  PartnerDriversRoute: PartnerDriversRoute,
  PartnerFleetRoute: PartnerFleetRoute,
  PartnerRequestsRoute: PartnerRequestsRoute,
  RegulatorAlertsRoute: RegulatorAlertsRoute,
  RegulatorComplianceRoute: RegulatorComplianceRoute,
  RegulatorExpiringRoute: RegulatorExpiringRoute,
  RegulatorNotificationsRoute: RegulatorNotificationsRoute,
  RegulatorOperatorsRoute: RegulatorOperatorsRoute,
  RegulatorReportsRoute: RegulatorReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  RegulatorIndexRoute: RegulatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
