import { apiFetch, apiDownload } from "./client";
import type { Paginated, UUID } from "./types";

// Operator-side logistics operations: transport requests, movements,
// deliveries, transactions, payments, incidents and the records around them.
// Mirrors beldium-backend/logistics (models.py / serializers.py at 1c04f36)
// field-for-field. Decimals arrive as strings, as DRF serialises them.
// References are generated by the server and read-only; `company` can't be
// changed after creation.

const BASE = "/logistics";

export interface OpsListQuery {
  page?: number | undefined;
  page_size?: number | undefined;
  search?: string | undefined;
  ordering?: string | undefined;
  [filter: string]: string | number | boolean | null | undefined;
}

type Stamp = { id: UUID; company: UUID; created_at: string; updated_at: string };
type Meta = { metadata: Record<string, unknown> };

// --- transport requests ------------------------------------------------------

export type TransportRequestStatus = "new" | "accepted" | "assigned" | "blocked" | "cancelled";

export interface TransportRequest extends Stamp, Meta {
  reference: string;
  rfq_id: string;
  transaction_id: string;
  movement_type: string;
  requester: string;
  miner: string;
  buyer: string;
  mineral: string;
  quantity: string;
  quantity_unit: string;
  quantity_display: string;
  origin: string;
  destination: string;
  required_pickup_at: string | null;
  status: TransportRequestStatus;
  blocked_reason: string;
}

export const listTransportRequests = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<TransportRequest>>(`${BASE}/transport-requests/`, { query });

export const getTransportRequest = (id: UUID) =>
  apiFetch<TransportRequest>(`${BASE}/transport-requests/${id}/`);

/** Creates the linked Movement (status `scheduled`); only `new` or `blocked` requests qualify. */
export const acceptTransportRequest = (id: UUID) =>
  apiFetch<TransportRequest>(`${BASE}/transport-requests/${id}/accept/`, { method: "POST" });

/** Sets status `cancelled` and stores the reason in `blocked_reason`. */
export const declineTransportRequest = (id: UUID, reason: string) =>
  apiFetch<TransportRequest>(`${BASE}/transport-requests/${id}/decline/`, {
    method: "POST",
    body: { reason },
  });

// --- movements ---------------------------------------------------------------

export type MovementStatus =
  | "scheduled"
  | "assigned"
  | "loading"
  | "in_transit"
  | "delayed"
  | "arrived"
  | "delivered"
  | "cancelled";

/** The backend's MOVEMENT_TRANSITIONS: anything else returns 409 invalid_movement_status_transition. */
export const MOVEMENT_TRANSITIONS: Record<MovementStatus, MovementStatus[]> = {
  scheduled: ["assigned", "cancelled"],
  assigned: ["loading", "in_transit", "cancelled"],
  loading: ["in_transit", "delayed", "cancelled"],
  in_transit: ["delayed", "arrived", "cancelled"],
  delayed: ["in_transit", "arrived", "cancelled"],
  arrived: ["delivered"],
  delivered: [],
  cancelled: [],
};

export interface Movement extends Stamp, Meta {
  reference: string;
  request: UUID | null;
  batch_id: string;
  rfq_id: string;
  transaction_id: string;
  movement_type: string;
  miner: string;
  buyer: string;
  mineral: string;
  quantity: string;
  quantity_unit: string;
  quantity_display: string;
  origin: string;
  destination: string;
  vehicle: UUID | null;
  vehicle_registration?: string | undefined;
  driver: UUID | null;
  driver_name?: string | undefined;
  pickup_at: string | null;
  eta_at: string | null;
  delivered_at: string | null;
  status: MovementStatus;
  last_latitude: string | null;
  last_longitude: string | null;
  last_gps_at: string | null;
}

export const listMovements = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<Movement>>(`${BASE}/movements/`, { query });

export const getMovement = (id: UUID) => apiFetch<Movement>(`${BASE}/movements/${id}/`);

/**
 * Rejected (409) for expired insurance, roadworthiness, licence or medical,
 * a vehicle/driver already on an active movement, another company's assets,
 * or a restricted service scope. The error message says which.
 */
export const assignMovement = (
  id: UUID,
  input: { vehicle?: UUID | undefined; driver?: UUID | undefined },
) => apiFetch<Movement>(`${BASE}/movements/${id}/assign/`, { method: "POST", body: input });

export interface MovementStatusInput {
  status: MovementStatus;
  occurred_at?: string | undefined;
  latitude?: string | undefined;
  longitude?: string | undefined;
  eta_at?: string | undefined;
  /** Recorded as an operations event on the company's feed. */
  note?: string | undefined;
}

export const setMovementStatus = (id: UUID, input: MovementStatusInput) =>
  apiFetch<Movement>(`${BASE}/movements/${id}/status/`, { method: "POST", body: input });

// --- deliveries ----------------------------------------------------------------

export type DeliveryStatus =
  "pending" | "in_transit" | "arrived" | "completed" | "variance_flagged" | "cancelled";

export interface Delivery extends Stamp, Meta {
  reference: string;
  movement: UUID;
  movement_reference: string;
  transaction_id: string;
  destination_type: string;
  destination: string;
  expected_quantity: string;
  received_quantity: string | null;
  quantity_unit: string;
  receipt_reference: string;
  arrived_at: string | null;
  custody_transferred_at: string | null;
  status: DeliveryStatus;
  variance: string | null;
}

export const listDeliveries = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<Delivery>>(`${BASE}/deliveries/`, { query });

/**
 * Records the received quantity. The server sets `completed`, or
 * `variance_flagged` when it differs from expected by more than
 * `metadata.quantity_tolerance` (default 0).
 */
export const completeDelivery = (
  id: UUID,
  input: {
    received_quantity: string;
    receipt_reference?: string | undefined;
    custody_transferred_at?: string | undefined;
  },
) => apiFetch<Delivery>(`${BASE}/deliveries/${id}/complete/`, { method: "POST", body: input });

// --- transactions & payments ---------------------------------------------------

export interface LogisticsTransaction extends Stamp, Meta {
  transaction_id: string;
  rfq_id: string;
  buyer: string;
  miner: string;
  material: string;
  quantity: string;
  quantity_unit: string;
  origin: string;
  destination: string;
  movement: UUID | null;
  movement_reference?: string | undefined;
  transport_fee: string;
  stage: string;
  delivery_status: string;
  payment_status: string;
}

export const listTransactions = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<LogisticsTransaction>>(`${BASE}/operations-transactions/`, { query });

export const getTransaction = (id: UUID) =>
  apiFetch<LogisticsTransaction>(`${BASE}/operations-transactions/${id}/`);

export type PaymentStatus =
  "not_invoiced" | "invoice_raised" | "submitted" | "part_paid" | "paid" | "overdue";

export interface LogisticsPayment extends Stamp, Meta {
  reference: string;
  transaction: UUID | null;
  transaction_id?: string | undefined;
  movement: UUID | null;
  movement_reference?: string | undefined;
  invoice_reference: string;
  job_value: string;
  due_amount: string;
  paid_amount: string;
  outstanding_amount: string;
  status: PaymentStatus;
  payment_date: string | null;
}

export const listPayments = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<LogisticsPayment>>(`${BASE}/operations-payments/`, { query });

// --- incidents -------------------------------------------------------------------

export type IncidentSeverity = "low" | "medium" | "high" | "critical";
export type IncidentStatus = "open" | "under_investigation" | "resolved" | "closed";

export interface Incident extends Stamp, Meta {
  reference: string;
  movement: UUID | null;
  movement_reference?: string | undefined;
  vehicle_registration?: string | undefined;
  driver_name?: string | undefined;
  incident_type: string;
  severity: IncidentSeverity;
  status: IncidentStatus;
  location: string;
  occurred_at: string;
  description: string;
  immediate_action: string;
  resolution: string;
}

/** Reference is generated by the server; status defaults to `open`. */
export interface NewIncidentInput {
  company: UUID;
  movement?: UUID | null | undefined;
  incident_type: string;
  severity: IncidentSeverity;
  location?: string | undefined;
  occurred_at: string;
  description: string;
  immediate_action?: string | undefined;
}

export const listIncidents = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<Incident>>(`${BASE}/incidents/`, { query });

export const reportIncident = (input: NewIncidentInput) =>
  apiFetch<Incident>(`${BASE}/incidents/`, { method: "POST", body: input });

export const resolveIncident = (
  id: UUID,
  input: { resolution: string; status?: IncidentStatus | undefined },
) => apiFetch<Incident>(`${BASE}/incidents/${id}/resolve/`, { method: "POST", body: input });

// --- documents, findings, quality -------------------------------------------------

export type OperationsDocumentStatus =
  "action_required" | "under_review" | "verified" | "expiring" | "expired" | "rejected";

export interface OperationsDocument extends Stamp, Meta {
  reference: string;
  name: string;
  document_type: string;
  related_asset: string;
  issue_date: string | null;
  expiry_date: string | null;
  verification_status: OperationsDocumentStatus;
  compliance_status: OperationsDocumentStatus;
  original_name: string;
  /** Absolute URL, or null when no file was attached. */
  download_url: string | null;
}

export const listOperationsDocuments = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<OperationsDocument>>(`${BASE}/operations-documents/`, { query });

export interface NewOperationsDocumentInput {
  company: UUID;
  name: string;
  document_type: string;
  related_asset?: string | undefined;
  issue_date?: string | undefined;
  expiry_date?: string | undefined;
  file: File;
}

/** Uploads go multipart (the file); JSON is accepted for metadata-only edits. */
export function uploadOperationsDocument(input: NewOperationsDocumentInput) {
  const form = new FormData();
  for (const [key, value] of Object.entries(input)) {
    if (value === undefined || value === "") continue;
    form.append(key, value instanceof File ? value : String(value));
  }
  return apiFetch<OperationsDocument>(`${BASE}/operations-documents/`, {
    method: "POST",
    body: form,
  });
}

export const downloadOperationsDocument = (doc: OperationsDocument) =>
  apiDownload(`${BASE}/operations-documents/${doc.id}/download/`, doc.original_name || doc.name);

export type ComplianceFindingStatus =
  "open" | "under_review" | "corrective_action_submitted" | "cleared";

export interface ComplianceFinding extends Stamp, Meta {
  reference: string;
  area: string;
  detail: string;
  action: string;
  owner: string;
  status: ComplianceFindingStatus;
  raised_at: string;
}

export const listFindings = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<ComplianceFinding>>(`${BASE}/compliance-findings/`, { query });

export const updateFinding = (
  id: UUID,
  patch: { action?: string; owner?: string; status?: ComplianceFindingStatus },
) =>
  apiFetch<ComplianceFinding>(`${BASE}/compliance-findings/${id}/`, {
    method: "PATCH",
    body: patch,
  });

export interface QualityRecord extends Stamp, Meta {
  transaction_id: string;
  sample_status: string;
  result: string;
  approval: string;
  handling: string;
  certificate: string;
  buyer_acceptance: string;
}

export const listQualityRecords = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<QualityRecord>>(`${BASE}/quality-records/`, { query });

// --- events & action items ------------------------------------------------------------

export interface OperationsEvent extends Stamp, Meta {
  occurred_at: string;
  text: string;
  sector: string;
  event_type: string;
  unread: boolean;
}

export const listOperationsEvents = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<OperationsEvent>>(`${BASE}/operations-events/`, { query });

export const markEventRead = (id: UUID) =>
  apiFetch<OperationsEvent>(`${BASE}/operations-events/${id}/mark-read/`, { method: "POST" });

export interface ActionItem extends Stamp, Meta {
  action: string;
  target: string;
  urgency: string;
  status: "open" | "done" | "dismissed";
  related_movement: UUID | null;
  movement_reference?: string | undefined;
}

export const listActionItems = (query: OpsListQuery = {}) =>
  apiFetch<Paginated<ActionItem>>(`${BASE}/action-items/`, { query });

export const completeActionItem = (id: UUID) =>
  apiFetch<ActionItem>(`${BASE}/action-items/${id}/complete/`, { method: "POST" });

// --- dashboard -------------------------------------------------------------------------

export interface OperationsDashboard {
  stats: {
    active_jobs: number;
    new_transport_requests: number;
    vehicles_assigned: number;
    drivers_active: number;
    awaiting_pickup: number;
    loading: number;
    in_transit: number;
    delayed_shipments: number;
    open_incidents: number;
    compliance_alerts: number;
    available_vehicles: number;
    /** The signed-in user's own unread compliance notifications. */
    unread_notifications: number;
    /** Unread operations events, shared across the company. */
    unread_events: number;
    tonnes_moved: string | number;
    outstanding_payments: string | number;
  };
  status_breakdown: { status: MovementStatus; count: number }[];
  action_items: ActionItem[];
  events: OperationsEvent[];
  active_movements: Movement[];
  transport_requests: TransportRequest[];
  filters: {
    movement_types: string[];
    statuses: string[];
    miners: string[];
    buyers: string[];
    minerals: string[];
  };
}

export const fetchOperationsDashboard = (signal?: AbortSignal) =>
  apiFetch<OperationsDashboard>(`${BASE}/operations_dashboard/`, { signal });
