/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppEnvironmentalRouteImport } from './routes/app.environmental'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppMonitoringRouteImport } from './routes/app.monitoring'
import { Route as AppNonconformitiesRouteImport } from './routes/app.nonconformities'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppProcessorsRouteImport } from './routes/app.processors'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppTraceabilityRouteImport } from './routes/app.traceability'
import { Route as AppApplicationsIdRouteImport } from './routes/app.applications.$id'
import { Route as AppProcessorsIdRouteImport } from './routes/app.processors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentalRoute = AppEnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppNonconformitiesRoute = AppNonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessorsRoute = AppProcessorsRouteImport.update({
  id: '/processors',
  path: '/processors',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTraceabilityRoute = AppTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AppProcessorsIdRoute = AppProcessorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProcessorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/processors': typeof AppProcessorsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/traceability': typeof AppTraceabilityRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/processors/$id': typeof AppProcessorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/processors': typeof AppProcessorsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/traceability': typeof AppTraceabilityRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/processors/$id': typeof AppProcessorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/processors': typeof AppProcessorsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/traceability': typeof AppTraceabilityRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/processors/$id': typeof AppProcessorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/applications'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/environmental'
    | '/app/incidents'
    | '/app/inspections'
    | '/app/monitoring'
    | '/app/nonconformities'
    | '/app/onboarding'
    | '/app/processors'
    | '/app/reports'
    | '/app/traceability'
    | '/app/applications/$id'
    | '/app/processors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/applications'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/environmental'
    | '/app/incidents'
    | '/app/inspections'
    | '/app/monitoring'
    | '/app/nonconformities'
    | '/app/onboarding'
    | '/app/processors'
    | '/app/reports'
    | '/app/traceability'
    | '/app/applications/$id'
    | '/app/processors/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/applications'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/environmental'
    | '/app/incidents'
    | '/app/inspections'
    | '/app/monitoring'
    | '/app/nonconformities'
    | '/app/onboarding'
    | '/app/processors'
    | '/app/reports'
    | '/app/traceability'
    | '/app/applications/$id'
    | '/app/processors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/environmental': {
      id: '/app/environmental'
      path: '/environmental'
      fullPath: '/app/environmental'
      preLoaderRoute: typeof AppEnvironmentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nonconformities': {
      id: '/app/nonconformities'
      path: '/nonconformities'
      fullPath: '/app/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processors': {
      id: '/app/processors'
      path: '/processors'
      fullPath: '/app/processors'
      preLoaderRoute: typeof AppProcessorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traceability': {
      id: '/app/traceability'
      path: '/traceability'
      fullPath: '/app/traceability'
      preLoaderRoute: typeof AppTraceabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/$id': {
      id: '/app/applications/$id'
      path: '/$id'
      fullPath: '/app/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/app/processors/$id': {
      id: '/app/processors/$id'
      path: '/$id'
      fullPath: '/app/processors/$id'
      preLoaderRoute: typeof AppProcessorsIdRouteImport
      parentRoute: typeof AppProcessorsRoute
    }
  }
}

interface AppApplicationsRouteChildren {
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
}

const AppApplicationsRouteChildren: AppApplicationsRouteChildren = {
  AppApplicationsIdRoute: AppApplicationsIdRoute,
}

const AppApplicationsRouteWithChildren = AppApplicationsRoute._addFileChildren(
  AppApplicationsRouteChildren,
)

interface AppProcessorsRouteChildren {
  AppProcessorsIdRoute: typeof AppProcessorsIdRoute
}

const AppProcessorsRouteChildren: AppProcessorsRouteChildren = {
  AppProcessorsIdRoute: AppProcessorsIdRoute,
}

const AppProcessorsRouteWithChildren = AppProcessorsRoute._addFileChildren(
  AppProcessorsRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEnvironmentalRoute: typeof AppEnvironmentalRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProcessorsRoute: typeof AppProcessorsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppTraceabilityRoute: typeof AppTraceabilityRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEnvironmentalRoute: AppEnvironmentalRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProcessorsRoute: AppProcessorsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppTraceabilityRoute: AppTraceabilityRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
